#!/bin/sh

ourInit() {
if [ -x /usr/sbin/invoke-rc.d ] && [ ! "`readlink /usr/sbin/invoke-rc.d`" = /bin/true ] ; then
  invoke-rc.d $1 $2
else
  /etc/init.d/$1 $2
fi
}

if [ -x "/etc/init.d/untangle-firmware-common" ]; then
  ourInit untangle-firmware-common restart
fi

# 12.2.1 upgrade NGFW-10303
# remove file if it exists
rm -f /etc/udev/rules.d/70-persistent-net.rules

# disable rsyslog by default on linksys
update-rc.d rsyslog disable

exit 0
