#!/bin/sh

LIST=/usr/share/untangle-nsis/copied-files
DIR="`pwd`"

cd /usr/share/untangle-nsis/
for i in `find . -type f` ; do 
    if [ ! -f /usr/share/nsis/$i ] ; then
        echo $i >> $LIST
        mkdir -p `dirname /usr/share/nsis/$i`
        cp -r $i /usr/share/nsis/$i
    fi
done

# Copy in the NSISKill DLL
cp /usr/share/untangle-nsis/Plugins/processwork.dll /usr/share/nsis/Plugins/

cd ${DIR}
unset DIR