# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1177528839);
user_pref("app.update.lastUpdateTime.background-update-timer", 1177528839);
user_pref("browser.download.manager.showWhenStarting", false);
user_pref("browser.search.selectedEngine", "Google");
user_pref("extensions.lastAppVersion", "1.5");
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1");
user_pref("network.cookie.prefsMigrated", true);
user_pref("security.warn_submit_insecure", false);
