#! /bin/sh

chown -R rbot /home/rbot
mkdir -p /home/rbot/.ssh
chmod 700 /home/rbot/.ssh

RBOT_CONF_FILE=/home/rbot/.rbot/conf.yaml
KEY=`cat /usr/share/metavize/activation.key`
KEY=${KEY:-1234:5678:abcd:efgh}

perl -npe 's/<>/'$KEY'/' $RBOT_CONF_FILE.template >| $RBOT_CONF_FILE

#DEBHELPER#

exit 0