#! /bin/bash

set -e

NAME="client"
ARCH="$(dpkg-architecture -qDEB_BUILD_ARCH)"
#PACKAGES="curl,iputils-ping,nvi" # bare minimum

if lxc-info -n $NAME > /dev/null ; then
  echo "LXC container $NAME already exists"
else
  echo "Creating LXC container ${NAME}..."
  lxc-create -n $NAME -t download -- -d debian -r jessie -a $ARCH
  echo "LXC container ${NAME} is ready"
fi
