#! /bin/bash

NAME="client"

echo "Setting DNS for containe ${NAME} to 192.0.2.1"
echo nameserver 192.0.2.1 >| /var/lib/lxc/${NAME}/rootfs/etc/resolv.conf

echo "Setting SSH configuration"
cp /etc/ssh/sshd_config /var/lib/lxc/${NAME}/rootfs/etc/ssh/sshd_config

echo "Starting LXC container ${NAME} in the background..."
lxc-start -d -n $NAME
echo "You can attach to it via lxc-attach -n $NAME"
