#! /bin/sh

FDIR=/usr/share/fuzzyocr-ut

# copy in config files
cp -p $FDIR/FuzzyOcr.cf /etc/mail/spamassassin
cp -p $FDIR/FuzzyOcr.pm /usr/share/perl5/Mail/SpamAssassin/Plugin/

# setting of pre314 var moved to spamc-mv.postinst

# reload SA
/etc/init.d/spamassassin reload

exit 0
