#! /bin/sh

set -e

PART=1 # we work on the 1st partition
FLAG_PART="/var/lib/untangle-resized-part"
FLAG_FS="/var/lib/untangle-resized-fs"

## main

# exit if we've already done the job
[ ! -f $FLAG_FS ] || exit 0


# what device to operate on
disk=${1:-"/dev/sda"}
device=${disk}$PART

if [ ! -f $FLAG_PART ] ; then # no partition resize yet
  # get the start of the PART partition on that device
  start=$(fdisk -l $disk | perl -ne 'if (m|^/|) { s/.*?\s(\d+).*/$1/ ; print }')

  # resize that PART partition so it uses the entire space
  { fdisk $disk <<EOF
p
d
n
p
$PART
$start

p
w
EOF
  } || true
  date -Iseconds > $FLAG_PART
elif [ ! -f $FLAG_FS ] ; then # partition already resized, let's take care of the FS now
  # resize FS (in the background)
  resize2fs $device &

  # write flag
  date -Iseconds > $FLAG_FS
fi
