#! /bin/sh

set -x

modprobe xt_conntrack
modprobe xt_comment
modprobe xt_multiport
modprobe xt_policy
modprobe xt_socket
modprobe xt_mac
modprobe xt_IMQ

modprobe ip6_tables
modprobe nf_conntrack_ipv6

exit 0
