#! /bin/sh

set -x

if [ -f /etc/inittab ] ; then
    cp -f /etc/inittab /tmp/inittab.orig

    # disable getty on local terminals
    sed -i -e '/^[0-9].*respawn.*getty.*/ s/^/#/g' /etc/inittab

    # enable serial console FIXME
    sed -i -e '/^#.* ttyS0 .*/ s/.*/T0:23:respawn:\/sbin\/getty -L ttyS0 115200 vt100/' /etc/inittab

    # if inittab changed, tell init
    if ! cmp -s /etc/inittab /tmp/inittab.orig; then
        kill -HUP 1
    fi

    rm -f /tmp/inittab.orig
fi

exit 0
