#! /bin/bash

set -x

# FIXME does not work
MAC_ADDR="`/usr/bin/nvram /dev/mtdblock1 get 0:macaddr`"

if [ -z "${MAC_ADDR}" ] ; then
    echo "Unable to determine MAC address"
else
    /usr/bin/nvram /dev/mtdblock1 set et1macaddr ${MAC_ADDR}
fi

/usr/bin/nvram /dev/mtdblock1 set vlan2ports "4 7u"
/usr/bin/nvram /dev/mtdblock1 set vlan2hwname "et1"
/usr/bin/nvram /dev/mtdblock1 set vlan1hwname "et1"
/usr/bin/nvram /dev/mtdblock1 set vlan1ports "0 1 2 3 5 7*"
/usr/bin/nvram /dev/mtdblock1 set et0macaddr ""
/usr/bin/nvram /dev/mtdblock1 set et0phyaddr ""
/usr/bin/nvram /dev/mtdblock1 set et0mdcport ""
/usr/bin/nvram /dev/mtdblock1 set et2macaddr ""
/usr/bin/nvram /dev/mtdblock1 set et2phyaddr ""
/usr/bin/nvram /dev/mtdblock1 set et2mdcport ""
