#! /bin/sh

set -x
set -e

# load modules for ethernet NIC
depmod -a
modprobe emf
modprobe igs
modprobe et
modprobe switch-core
modprobe switch-robo
modprobe dhd
modprobe wl

lsmod
ip ad

# disable switch
echo 0 >| /proc/switch/eth0/enable

# reset config
echo 1 >| /proc/switch/eth0/reset

# eth0 up
ip link set eth0 up

CPUPORT="`cat /proc/switch/eth0/cpuport | tr -d '[[:space:]]'`"

# CPU port is usually 8 or 7, it seems to be different per appliance

# ports 0,1,2,3,5 are the LAN ports
# port 5 is actually ports 5-8 labeled on the appliance

# ports 0,1,2,3,5 (LAN) -> vlan 2
echo "0\t1\t2\t3\t5\t${CPUPORT}t" >| /proc/switch/eth0/vlan/2/ports

# port 4 (WAN) -> vlan 1
echo "4\t${CPUPORT}t" >| /proc/switch/eth0/vlan/1/ports

# enable switch
echo 1 >| /proc/switch/eth0/enable


exit 0
