#! /bin/sh

DISK=$( df / | awk -F/ '/dev/ {gsub(/p?[0-9] .+/, "", $3) ; print $3}')
DEVICE="/dev/${DISK}"

echo 1 > /sys/block/${DISK}/device/rescan

if growpart ${DEVICE} 1 ; then
  partprobe
  resize2fs ${DEVICE}1
fi

exit 0
