export default {
  vlan: {
    name: '',
    type: 'VLAN',
    configType: 'ADDRESSED',
    enabled: true,
    wan: false,
    v4ConfigType: 'DISABLED',
    v6ConfigType: 'DISABLED',
  },

  bridge: {
    name: '',
    type: 'BRIDGE',
    configType: 'BRIDGED',
    enabled: true,
    wan: false,
    v4ConfigType: 'STATIC',
    v6ConfigType: 'DISABLED',
  },

  openvpn: {
    name: '',
    type: 'OPENVPN',
    configType: 'ADDRESSED',
    boundInterfaceId: 0, // any WAN
    enabled: true,
    wan: true,
    natEgress: true,
    new: true,
    openvpnConfFile: { contents: null, encoding: 'base64' },
    openvpnUsernamePasswordEnabled: false,
    openvpnUsername: null,
    openvpnPasswordBase64: null,
    openvpnPeerDns: false,
  },

  wireguard: {
    name: '',
    type: 'WIREGUARD',
    configType: 'ADDRESSED',
    boundInterfaceId: 0, // any WAN
    enabled: true,
    wan: true,
    natEgress: true,
    new: true,
    wireguardType: 'ROAMING',
    wireguardAddresses: [{ address: '172.31.229.1', prefix: '24' }],
    wireguardPort: 51820,
    wireguardPeers: [
      {
        publicKey: null,
        host: null,
        port: null,
        allowedIps: [{ address: '0.0.0.0', prefix: 0 }],
        // peer 'presharedKey' is not implemented and used yet
        presharedKey: null,
        // peer 'keepalive' defaults to 60 seconds (not shown and not changeable)
        keepalive: 60,
        // peer 'routeAllowedIps' always true (not shown and not changeable)
        routeAllowedIps: true,
      },
    ],
    wireguardPrivateKey: null,
    wireguardPublicKey: null,
  },

  ipsec: {
    name: '',
    type: 'IPSEC',
    configType: 'ADDRESSED',
    boundInterfaceId: 0,
    enabled: true,
    wan: true,
    natEgress: false,
    new: true,
    mtu: 1500,
    routeMtu: true,
    ipsec: {
      authentication: {
        shared_secret: '',
        type: 'shared_secret',
      },
      debug: 2,
      keyexchange: 'ikev2',
      local: {
        gateway: '%any',
        networks: [],
      },
      remote: {
        gateway: '',
        networks: [],
      },
      singleSubnetNegotiation: true,
      phase1: [
        {
          encryption: 'aes256',
          hash: 'sha1',
          group: 'modp2048',
        },
      ],
      phase2: [
        {
          encryption: 'aes256gcm128',
          hash: 'sha1',
          group: 'modp2048',
        },
      ],
      phase1Lifetime: '28800', // default p1 lifetime
      phase2Lifetime: '3600', // default p2 lifetime
    },
  },
  ipsec_network: {
    network: '0.0.0.0',
    prefix: 0,
  },
  v4_alias: {
    v4Address: null,
    v4Prefix: 24, // use 24 as default
  },
  v6_alias: { v6Address: null, v6Prefix: null },
  dhcp_options: [
    { value: 1, text: 'netmask', description: '' },
    { value: 2, text: 'time-offset', description: '' },
    { value: 3, text: 'router', description: '' },
    { value: 6, text: 'dns-server', description: '' },
    { value: 7, text: 'log-server', description: '' },
    { value: 9, text: 'lpr-server', description: '' },
    { value: 13, text: 'boot-file-size', description: '' },
    { value: 15, text: 'domain-name', description: '' },
    { value: 16, text: 'swap-server', description: '' },
    { value: 17, text: 'root-path', description: '' },
    { value: 18, text: 'extension-path', description: '' },
    { value: 19, text: 'ip-forward-enable', description: '' },
    { value: 20, text: 'non-local-source-routing', description: '' },
    { value: 21, text: 'policy-filter', description: '' },
    { value: 22, text: 'max-datagram-reassembly', description: '' },
    { value: 23, text: 'default-ttl', description: '' },
    { value: 26, text: 'mtu', description: '' },
    { value: 27, text: 'all-subnets-local', description: '' },
    { value: 31, text: 'router-discovery', description: '' },
    { value: 32, text: 'router-solicitation', description: '' },
    { value: 33, text: 'static-route', description: '' },
    { value: 34, text: 'trailer-encapsulation', description: '' },
    { value: 35, text: 'arp-timeout', description: '' },
    { value: 36, text: 'ethernet-encap', description: '' },
    { value: 37, text: 'tcp-ttl', description: '' },
    { value: 38, text: 'tcp-keepalive', description: '' },
    { value: 40, text: 'nis-domain', description: '' },
    { value: 41, text: 'nis-server', description: '' },
    { value: 42, text: 'ntp-server', description: '' },
    { value: 44, text: 'netbios-ns', description: '' },
    { value: 45, text: 'netbios-dd', description: '' },
    { value: 46, text: 'netbios-nodetype', description: '' },
    { value: 47, text: 'netbios-scope', description: '' },
    { value: 48, text: 'x-windows-fs', description: '' },
    { value: 49, text: 'x-windows-dm', description: '' },
    { value: 58, text: 'T1', description: '' },
    { value: 59, text: 'T2', description: '' },
    { value: 60, text: 'vendor-class', description: '' },
    { value: 64, text: 'nis+-domain', description: '' },
    { value: 65, text: 'nis+-server', description: '' },
    { value: 66, text: 'tftp-server', description: '' },
    { value: 67, text: 'bootfile-name', description: '' },
    { value: 68, text: 'mobile-ip-home', description: '' },
    { value: 69, text: 'smtp-server', description: '' },
    { value: 70, text: 'pop3-server', description: '' },
    { value: 71, text: 'nntp-server', description: '' },
    { value: 74, text: 'irc-server', description: '' },
    { value: 77, text: 'user-class', description: '' },
    { value: 80, text: 'rapid-commit', description: '' },
    { value: 93, text: 'client-arch', description: '' },
    { value: 94, text: 'client-interface-id', description: '' },
    { value: 97, text: 'client-machine-id', description: '' },
    { value: 119, text: 'domain-search', description: '' },
    { value: 120, text: 'sip-server', description: '' },
    { value: 121, text: 'classless-static-route', description: '' },
    { value: 125, text: 'vendor-id-encap', description: '' },
    { value: 255, text: 'server-ip-address', description: '' },
  ],
  wg_ip_config: { address: null, prefix: 24 },
  ipSecEncryptionOptions: [
    '3des',
    'aes128',
    'aes192',
    'aes256',
    'aes128gcm64',
    'aes192gcm64',
    'aes256gcm64',
    'aes128gcm96',
    'aes192gcm96',
    'aes256gcm96',
    'aes128gcm128',
    'aes192gcm128',
    'aes256gcm128',
  ],
  ipSecHashOptions: ['md5', 'sha1', 'sha256', 'sha384', 'sha512'],
  ipSecGroupOptions: [
    { value: 'modp768', text: 'modp768 [DH1]' },
    { value: 'modp1024', text: 'modp1024 [DH2]' },
    { value: 'modp1536', text: 'modp1536 [DH5]' },
    { value: 'modp2048', text: 'modp2048 [DH14]' },
    { value: 'modp3072', text: 'modp3072 [DH15]' },
    { value: 'modp4096', text: 'modp4096 [DH16]' },
    { value: 'modp6144', text: 'modp6144 [DH17]' },
    { value: 'modp8192', text: 'modp8192 [DH18]' },
    { value: 'modp1024s160', text: 'modp1024s160 [DH22]' },
    { value: 'modp2048s224', text: 'modp2048s224 [DH23]' },
    { value: 'modp2048s256', text: 'modp2048s256 [DH24]' },
  ],
}
