#! /bin/bash

mkdir -p /var/log/untangle-net-alpaca
exec >> /var/log/untangle-net-alpaca/dnsmasq.log 2>&1

ACTION=${1:-restart}

if [ "${ACTION}x" == "stop" ]; then
    /bin/echo -e "[DEBUG:`date`] Stopping DNS masq"
    /etc/init.d/dnsmasq stop
    exit 0
fi

FORCE_RESTART=${2:-true}
DNSMASQ_HASH="/var/run/untangle-net-alpaca/dnsmasq-hash"

NEW_HASH=`mktemp`

mkdir -p `dirname ${DNSMASQ_HASH}`

## Strip out newlines and comments
for t in /etc/untangle-net-alpaca/dnsmasq-hosts /etc/hosts /etc/dnsmasq.conf /etc/resolv.conf ; do
    sed -e '/^#/d' -e '/^$/d' /etc/dnsmasq.conf | md5sum | awk "{ print \$1 \" $t\" }" >> ${NEW_HASH}
done

currentPid=`pidof dnsmasq`
expectedPid=`cat /var/run/dnsmasq.pid`

## Always do a restart
if [ -z "${currentPid}" ] || [ "${currentPid}x" != "${expectedPid}x" ]; then
    /bin/echo -e "[DEBUG:`date`] Forcing a restart of dnsmasq"
    FORCE_RESTART=true
fi

if [ ${FORCE_RESTART} == "false" ] && [ -f ${DNSMASQ_HASH} ]; then
    ## If they are the same do nothing
    diff ${NEW_HASH} ${DNSMASQ_HASH} > /dev/null 2>&1 && { 
        /bin/echo -e "[DEBUG:`date`] Skipping dnsmasq restart" 
        rm -f ${NEW_HASH}
        exit 0 
    }

    ## If the host files differ, just send a SIGHUP
    diff -I '\/etc\/hosts' -I '/\etc\/untangle-net-alpaca\/dnsmasq-hosts' ${NEW_HASH} ${DNSMASQ_HASH} > /dev/null 2>&1 && {
        /bin/echo -e "[DEBUG:`date`] sending dnsmasq SIGHUP to reload host file." 
        kill -HUP ${currentPid}
        mv ${NEW_HASH} ${DNSMASQ_HASH}
        exit 0
    }
fi

## Otherwise force a restart
/bin/echo -e "[DEBUG:`date`] Restarting dnsmasq." 
/etc/init.d/dnsmasq restart

mv ${NEW_HASH} ${DNSMASQ_HASH}

