#!/bin/dash

mkdir -p /var/log/untangle-net-alpaca
exec >> /var/log/untangle-net-alpaca/iptables.log 2>&1

iptables_debug()
{
   echo /sbin/iptables $*
   /sbin/iptables $*
}

iptables_debug_onerror()
{
    ## Ignore -N errors
    /sbin/iptables $* || {
        [ "${3}x" != "-Nx" ] && echo "Failed: /sbin/iptables $*"
    }

    true
}

IPTABLES=/sbin/iptables

#IPTABLES="iptables_debug"

IPTABLES=iptables_debug_onerror

ebtables_debug()
{
    echo /sbin/ebtables $*
    /sbin/ebtables $*
}

EBTABLES=/sbin/ebtables
# EBTABLES=ebtables_debug

get_ip_addresses()
{
    local t_intf=$1

    if [ -z "${t_intf}" ]; then return; fi

    ## Throw away error data.
    ip -f inet addr show ${t_intf} 2>/dev/null | \
        awk '/inet/ { ip = $2 ; sub( /\/.*$/, "", ip ) ; print ip  }'
}

run_iptables_scripts()
{
    local t_script
    local t_ran_script=""

    if [ ! -d ${IPTABLES_DIRECTORY} ]; then
        echo "[`date`] ${IPTABLES_DIRECTORY} does not exist."
        return 0
    fi
    
    ## Would use run-parts, but that doesn't maintain environment variables 
    ## or the iptables_debug function.

    ## Do not run any of the dpkg backup files.
    for t_script in `run-parts --list --lsbsysinit ${IPTABLES_DIRECTORY} | sort` ; do
        . ${t_script}
        t_ran_script="true"
    done
    
    if [ "${t_ran_script}x" != "truex" ]; then
        echo "[`date`] ${IPTABLES_DIRECTORY} is empty."
    fi
}

IPTABLES_DIRECTORY=/etc/untangle-net-alpaca/iptables-rules.d

run_iptables_scripts

echo "" > /dev/null
