#!/bin/dash

mkdir -p /var/log/untangle-net-alpaca
exec >> /var/log/untangle-net-alpaca/iptables.log 2>&1

iptables_debug()
{
   echo /sbin/iptables $*
   /sbin/iptables $*
}

IPTABLES=/sbin/iptables

IPTABLES="iptables_debug"

IPTABLES_DIRECTORY=/etc/untangle-net-alpaca/iptables-rules.d

if [ ! -d ${IPTABLES_DIRECTORY} ]; then
    echo "${IPTABLES_DIRECTORY} does not exist."
    exit 0
fi

for t in ${IPTABLES_DIRECTORY}/* ; do . $t ; done

## run-parts ${IPTABLES_DIRECTORY}
