#!/bin/dash

##Add static routes rules
current_hostname=`hostname`

MARKER="ut-marker.example.com"
OLD_MARKER="ut-marker.example.com"

update_hosts()
{
    local t_address
    local t_host_script=" -e '\$a 127.0.0.1 ${current_hostname} ${MARKER}' "

    ## a dubious technique, at best.
    echo sed -i -e "/${MARKER}/d" -e "/${OLD_MARKER}/d" ${t_host_script} /etc/hosts | sh
}

if [ -z "${current_hostname}" ]; then
    echo "[`date`] hostname is not available"
    exit 0
fi

update_hosts

exit 0