#!/bin/dash

##Add static routes rules
current_hostname=`hostname`

MARKER="hostname.marker.untangle.com"
OLD_MARKER="ut-marker.example.com"

update_hosts()
{
    local t_address
    local t_host_script=""
   
    local t_temp=`mktemp`
    local t_dest="/etc/hosts"

    t_host_script="print \"127.0.0.1 ${current_hostname} ${MARKER}\";"
    
    ## Remove the existing hostname entries and update the new one.
    awk '!'"/(${MARKER}|${OLD_MARKER})/ { print \$0 }; END { ${t_host_script} }" ${t_dest} > ${t_temp}
    chmod 744 ${t_temp}
    mv ${t_temp} ${t_dest}
}

if [ -z "${current_hostname}" ]; then
    echo "[`date`] hostname is not available"
    exit 0
fi

update_hosts

exit 0
