#!/bin/dash

## Add entries for the hostname
current_hostname=`hostname`

MARKER="hostname.marker.untangle.com"
OLD_MARKER="ut-marker.example.com"

## This gets all addresses.
get_addresses()
{
    ip addr show | awk '/^[0-9]/ { current_intf=$2 } ; /inet/ { $ip = $2 ; sub( /\/.*$/, "", $ip ) ; if ( current_intf != "dummy0:" && current_intf != "utun:" && current_intf != "lo:" ) print $ip  }'
}

update_dnsmasq_hosts()
{
    local t_address
    local t_host_script=""
   
    local t_temp=`mktemp`
    local t_dest="/etc/untangle-net-alpaca/dnsmasq-hosts"

    for t_address in `get_addresses` ; do
        t_host_script="${t_host_script} print \"${t_address}  ${current_hostname} ${MARKER}\";"
    done
    
    ## Remove the existing hostname entries and update the new one.
    awk '!'"/(${MARKER}|${OLD_MARKER})/ { print \$0 }; END { ${t_host_script} }" ${t_dest} > ${t_temp}
    chmod 744 ${t_temp}
    mv ${t_temp} ${t_dest}
}

if [ -z "${current_hostname}" ]; then
    echo "[`date`] hostname is not available"
    exit 0
fi

short_name=${current_hostname%%.*}

if [ "${short_name}x" != "${current_hostname}x" ]; then
    current_hostname="${short_name} ${current_hostname}" ;
fi

update_dnsmasq_hosts

currentPid=`pidof dnsmasq`

## Notify dnsmasq of the changes.
if [ -n "${currentPid}" ]; then kill -HUP ${currentPid} ; fi 

exit 0
