#!/bin/dash

UNTANGLE_PRIORITY_BASE="36"
UNTANGLE_PRIORITY_MULTIWAN="366"

UNTANGLE_MULTIWAN_SHIFT=8
UNTANGLE_MULTIWAN_MASK=0xFF00

UNTANGLE_MAX_INTERFACE=250

debug()
{
    echo "[DEBUG:`date`] $*"
}

flush_multiwan_ip_rules()
{
    local t_priority

    for t_priority in `ip rule show | awk "/^${UNTANGLE_PRIORITY_MULTIWAN}[0-9][0-9][0-9]:/ { sub( \":\", \"\", \\$1 ) ; print \\$1 }"`; do
        ip rule del priority ${t_priority}
    done
}

expected_multiwan_ip_rules()
{
    local t_index
    for t_index in `seq 1 ${UNTANGLE_MAX_INTERFACE}` ; do
        printf "${UNTANGLE_PRIORITY_MULTIWAN}%02d:\tfrom all fwmark %#x/%#x lookup uplink.%d \n" ${t_index} \
            $(( ${t_index} << ${UNTANGLE_MULTIWAN_SHIFT} )) ${UNTANGLE_MULTIWAN_MASK} \
            ${t_index}
    done
}

current_multiwan_ip_rules()
{
    ip rule show | awk "/^${UNTANGLE_PRIORITY_MULTIWAN}[0-9][0-9]:/ { print }" 
}

## This script updates the state of the system so that MULTIWAN can
## route traffic through the different interfaces.
insert_multiwan_ip_rules()
{
    local t_index
    local t_priority
    for t_index in `seq 1 ${UNTANGLE_MAX_INTERFACE}` ; do
        t_priority=`printf "${UNTANGLE_PRIORITY_MULTIWAN}%03d" ${t_index}`
        ip rule add priority  ${t_priority} \
            fwmark $(( ${t_index} << ${UNTANGLE_MULTIWAN_SHIFT} ))/${UNTANGLE_MULTIWAN_MASK} \
            lookup uplink.${t_index} 
    done
}

insert_uplink_tables()
{
    local t_temp
    local t_index

    grep -q "${IP_ROUTE_TABLE_MARKER}" ${IP_RT_TABLES} && return
    
    t_temp=`mktemp`
    
    echo "# ${IP_ROUTE_TABLE_MARKER} MultiWAN uplink tables" >> ${t_temp}

    for t_index in `seq 1 ${UNTANGLE_MAX_INTERFACE}`; do
        /bin/echo -e "$((${IP_RT_TABLE_BASE} + ${t_index}))\t${TABLE_PREFIX}${t_index}" >> ${t_temp}
    done
    
    sed -i -e '/uplink/d'  -e "/MultiWAN uplink tables/d" ${IP_RT_TABLES}
    cat ${t_temp} >> ${IP_RT_TABLES}
    
    rm -f ${t_temp}
}

## Start of script
## It is very dangerous to change this once a revision has been released.
TABLE_PREFIX="uplink."
IP_ROUTE_TABLE_MARKER="version2"
IP_RT_TABLES="/etc/iproute2/rt_tables"
IP_RT_TABLE_BASE=64
insert_uplink_tables

##Add static routes rules
if [ -e /etc/untangle-net-alpaca/routes ] ; then 
    . /etc/untangle-net-alpaca/routes
fi

if [ "`expected_multiwan_ip_rules | md5sum`" = "`current_multiwan_ip_rules  | md5sum`" ]; then
    debug "ip rules are up to date."
else
    flush_multiwan_ip_rules
    insert_multiwan_ip_rules
fi

exit 0
