#!/bin/dash

UVM_PID="invalid"

queue_owner()
{
    if [ "${UVM_PID}x" != "invalidx" ]; then return ; fi
    
    UVM_PID="invalid"
    
    if [ ! -f /proc/net/netfilter/nfnetlink_queue ] ; then return ; fi

    local t_queue_pid=`awk -v queue=0 '{ if ( $1 == queue ) print $2 }' /proc/net/netfilter/nfnetlink_queue`
    
    if [ -z "${t_queue_pid}" ]; then return ; fi
    
    UVM_PID=${t_queue_pid}  
}

bunnicula_home()
{
    queue_owner
    
    if [ ! -f /proc/${UVM_PID}/cmdline ]; then return ; fi

    perl -pe 's/[^0-9=a-zA-Z\/\-\+\*\.]/\n/g' /proc/${UVM_PID}/cmdline 2>| /dev/null | \
        awk '/^-Dbunnicula.home=/ { gsub( "-Dbunnicula.home=", "" ) ; print }'
}

update_pppoe()
{
    local t_sub
    local t_pid
    local t_intf_name
    local t_connection_file
    local t_temp

    t_sub=""
    for t_pid in /var/run/ppp*.pid ; do
        [ -f "${t_pid}" ] || continue

        t_intf_name=`echo ${t_pid} | sed -e 's|/var/run/\([^\.]\+\)\.pid|\1|'`
        [ "${t_intf_name}" = "${t_pid}" ] && continue
        
        t_pid=`cat ${t_pid}`
        
        [  -f /proc/${t_pid}/cmdline ]  || continue
        t_connection_file=`cat "/proc/${t_pid}/cmdline" | tr '\000' '\001' | awk -v RS='\001' '/^connection./ { print }'`
        t_connection_file="/etc/ppp/peers/${t_connection_file}"
        [ -f ${t_connection_file} ] || continue
        
        t_index=`awk '/# *PPPOE_UPLINK_INDEX=/ { sub( "# *PPPOE_UPLINK_INDEX=", "" ); print ; exit }' \
            ${t_connection_file}`
        
        t_sub="sub( \":[^:]*:${t_index},\", \":${t_intf_name}:\" ${t_index} \",\" ) ; ${t_sub}"
    done
    
    [ -z "${t_sub}" ] && return 
    [ -f "${INTERFACE_PROPERTIES}" ] || return

    t_temp=`mktemp`

    [ -f ${t_temp} ] || return

    awk "/^com.untangle.interface-order=/ { ${t_sub} print ; next } ; { print }" \
        ${INTERFACE_PROPERTIES} > ${t_temp}

    diff -q ${t_temp} ${INTERFACE_PROPERTIES} || {
        echo "[DEBUG:`date`] Updating interface properties for PPPoE"
        mv ${t_temp} ${INTERFACE_PROPERTIES}
        chmod 0644  ${INTERFACE_PROPERTIES}
    }

    rm -f ${t_temp}
}

BUNNICULA_HOME=`bunnicula_home`

INTERFACE_PROPERTIES=/etc/untangle-net-alpaca/interface.properties

if [ -z "${BUNNICULA_HOME}" ]; then
    echo "[`date`] UVM is not running"
    exit 0
fi

## Bunnicula home points to <root>/usr/share/untangle/
UCLI=${BUNNICULA_HOME}/../../bin/ucli

if [ ! -f "${UCLI}" ]; then
    echo "[`date`] ${UCLI} does not exist."
    exit 0    
fi

update_pppoe

${UCLI} updateAddress

## Just in case these settings were lost.
ifconfig dummy0 192.0.2.42 netmask 255.255.255.0 up
if [ -f /proc/sys/net/ipv4/conf/utun/rp_filter ]; then
    ifconfig utun up
    echo 0 > /proc/sys/net/ipv4/conf/utun/rp_filter
else
    echo "[`date`] utun device not exist."
fi

exit 0
