#!/bin/dash

UVM_PID="invalid"

queue_owner()
{
    if [ "${UVM_PID}x" != "invalidx" ]; then return ; fi
    
    UVM_PID="invalid"
    
    if [ ! -f /proc/net/netfilter/nfnetlink_queue ] ; then return ; fi

    local t_queue_pid=`awk -v queue=0 '{ if ( $1 == queue ) print $2 }' /proc/net/netfilter/nfnetlink_queue`
    
    if [ -z "${t_queue_pid}" ]; then return ; fi
    
    UVM_PID=${t_queue_pid}  
}

bunnicula_home()
{
    queue_owner
    
    if [ ! -f /proc/${UVM_PID}/cmdline ]; then return ; fi

    perl -pe 's/[^0-9=a-zA-Z\/\-\+\*\.]/\n/g' /proc/${UVM_PID}/cmdline 2>| /dev/null | \
        awk '/^-Dbunnicula.home=/ { gsub( "-Dbunnicula.home=", "" ) ; print }'
}

update_guest_address()
{
    local t_external_interface
    UVM_VMWARE_IP=${UVM_VMWARE_IP:-/mnt/hgfs/untangle/guest_address}
    
    [ -d `dirname ${UVM_VMWARE_IP}` ] || return
    
    ## Determine the external interface
    ## First use try the default gateway.
    t_external_interface=`ip route show | awk '/^default/ { print $5 ; exit 0 }'`
    
    ## Next try the interfaces.properties file.
    [ -z "${t_external_interface}" ] && [ -f /etc/untangle-net-alpaca/interface.properties ] && {
        t_external_interface=`sed  -e '/^com.untangle.interface-order/!d' -e 's|^.*External:\([^:]*\):\?.*$|\1|' /etc/untangle-net-alpaca/interface.properties`
        
        [ -z "${t_external_interface}" ] && return
        
        [ -L "/sys/class/net/${t_external_interface}/brport/bridge" ] && {
            t_external_interface=$( basename `readlink /sys/class/net/eth0/brport/bridge` )
        }
    }
    
    [ -n "${t_external_interface}" ] && {
        ip -f inet addr show ${t_external_interface} 2>|/dev/null | awk '/inet/ { ip = $2 ; sub( /\/.*$/, "", ip ) ; print ip ; exit 0  }' > ${UVM_VMWARE_IP}
    }
}

## Run this script regardless of whether or not the UVM is running.
update_guest_address

BUNNICULA_HOME=`bunnicula_home`

if [ -z "${BUNNICULA_HOME}" ]; then
    echo "[`date`] UVM is not running"
    exit 0
fi

## Bunnicula home points to <root>/usr/share/untangle/
UCLI=${BUNNICULA_HOME}/../../bin/ucli

if [ ! -f "${UCLI}" ]; then
    echo "[`date`] ${UCLI} does not exist."
    exit 0    
fi

${UCLI} updateAddress

## Just in case these settings were lost.
ifconfig dummy0 192.0.2.42 netmask 255.255.255.0 up
if [ -f /proc/sys/net/ipv4/conf/utun/rp_filter ]; then
    ifconfig utun up
    echo 0 > /proc/sys/net/ipv4/conf/utun/rp_filter
else
    echo "[`date`] utun device not exist."
fi

exit 0
