#! /bin/bash

restartService() {
    local t_service=$1

    if [ ! -f /etc/init.d/${t_service} ];  then
        echo "[DEBUG:`date`] missing the service ${t_service}"
        return 0
    fi

    # run this non-blocking in the background
    /etc/init.d/${t_service} restart &
}

# Gotta wait a little while for the bridge to reconfigure
sleep 5

t0=$(date +%s)
restartService ntpdate
t1=$(($(date +%s) + 10))
if [ $t0 -gt $t1 ]; then
    echo "restarting alpaca because time went back"
    restartService untangle-net-alpaca
fi

restartService ntp-server

restartService spamassassin

# remote support is enabled if sshd us running
pidof sshd && restartService untangle-support-agent


