#!/bin/sh

if [ -f /usr/share/metavize/conf/trials/clamphish.expired ] ; then

    # trial already used - disable immediately
    /usr/bin/mcli disable clamphish-transform &> /dev/null &

else

    # change extraname to trial
    /usr/bin/mcli extraname clamphish-transform "Trial (30 days remain)" &> /dev/null &

    for i in `seq 29` ; do 
        echo "/usr/bin/mcli extraname clamphish-transform \"Trial ($((30-$i)) days remain)\"" | at +$i days &> /dev/null
    done

    # schedule disabling - this gets double checked by the cron job
    echo "/usr/bin/mvdisable clamphish-transform &> /dev/null" | at "+30 days" &> /dev/null
    mkdir -p /usr/share/metavize/conf/trials &> /dev/null
fi


exit 0
