#!/bin/sh

if [ -f /usr/share/metavize/conf/trials/portal.expired ] ; then

    # trial already used - disable immediately
    mcli disable portal-transform &> /dev/null &

else

    # change extraname to trial
    mcli extraname portal-transform "trial" &> /dev/null &

    # schedule disabling - this gets double checked by the cron job
    echo "/usr/bin/mvdisable portal-transform &> /dev/null" | at "+30 days" &> /dev/null
    mkdir -p /usr/share/metavize/conf/trials &> /dev/null
fi


exit 0
