#!/bin/dash

# eth1 and eth2 aren't "UP" according to debian because they are managed in the chroot environment
# As such, they won't be brought down.

# This script is a ghetto hack to bring down these interfaces
# This is needed because they are included in the bridge interface

if [ "$IFACE" = "networking_post_restart_hook" ] ; then
    echo
    
    if ps aux | grep -v grep | grep -q nas.eth1.pid ; then
        echo "Stopping eth1 wireless..."
        /usr/bin/brcm-wifi eth1 stop

        sleep 1
    fi

    if ps aux | grep -v grep | grep -q nas.eth2.pid ; then
        echo "Stopping eth2 wireless..."
        /usr/bin/brcm-wifi eth2 stop

        sleep 1
    fi
fi

exit 0
