.\"     Title: RBOT\-MV
.\"    Author: Marc Dequ\\[`e]nes
.\" Generator: DocBook XSL Stylesheets v1.71.0 <http://docbook.sf.net/>
.\"      Date: 20041220
.\"    Manual: 
.\"    Source: 
.\"
.TH "RBOT\-MV" "1" "20041220" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
rbot\-mv \- IRC bot written in ruby
.SH "SYNOPSIS"
.HP 8
\fBrbot\-mv\fR [[\fB\-d\fR] | [\fB\-\-debug\fR] | [\fB\-h\fR] | [\fB\-\-help\fR] | [\fB\-v\fR] | [\fB\-\-version\fR]] [confdir]
.SH "DESCRIPTION"
.PP
\fBrbot\-mv\fR
starts the Rbot\-Mv (ruby IRC bot).
.SH "OPTIONS"
.PP
These programs follow the usual
GNU
command line syntax, with long options starting with two dashes (`\-'). A summary of options is included below. For a complete description, see the
Info
files.
.PP
\fB\-d\fR \fB\-\-debug\fR
.RS 3n
Display debug information (very verbose).
.RE
.PP
\fIconfdir\fR
.RS 3n
Path to the directory where are stored the bot's configuration files.
.RE
.PP
\fB\-h\fR \fB\-\-help\fR
.RS 3n
Show summary of options.
.RE
.PP
\fB\-v\fR \fB\-\-version\fR
.RS 3n
Display version information.
.RE
.SH "AUTHOR"
.PP
This manual page was written by Marc Dequ\\[`e]nes (Duck)
<Duck@DuckCorp.org>
for the
Debian(TM)
system (but may be used by others). Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 2 any later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL.
.SH "AUTHOR"
.PP
\fBMarc Dequ\\[`e]nes\fR
.sp -1n
.IP "" 3n
Author.
.SH "COPYRIGHT"
Copyright \(co 2004 Marc Dequ\\[`e]nes (Duck)
.br

