#!/bin/sh

SERVICE=${DPKG_MAINTSCRIPT_PACKAGE}

ourInit() {
if [ -x /usr/sbin/invoke-rc.d ] && [ ! "`readlink /usr/sbin/invoke-rc.d`" = /bin/true ] ; then
  invoke-rc.d $1 $2
else
  /etc/init.d/$1 $2
fi
}

if [ -x "/etc/init.d/${SERVICE}" ]; then
  update-rc.d ${SERVICE} defaults 10 >/dev/null # early on
  ourInit ${SERVICE} restart
fi
    
exit 0
