#!/bin/sh

# this is creates the default wizard settings for the buffalo wxr1900



if [ ! -f /usr/share/untangle/conf/wizard.js ] ; then

   echo "Initializing default wizard settings for Buffalo WXR 1900..."

   mkdir -p /usr/share/untangle/conf
   cat > /usr/share/untangle/conf/wizard.js <<EOF
{
    "javaClass": "com.untangle.uvm.WizardSettings",
    "steps": [
        "Welcome",
        "ServerSettings",
        "AutoUpgrades",
        "Complete"
    ],
    "wizardComplete": false
}
EOF

   echo "Initializing default wizard settings for Buffalo WXR 1900...done"

fi

