#!/bin/bash
##
## Rebuild the snort rules package distributed with new systems and updates
##
## Want to do the following:
## -  Include the latest defaults.js template.
## -  Remove precompiled rules that aren't used for our platform to save space
##

if [[ "$PWD" != *"untangle-snort-config" ]]
then
    echo "Must run from untangle-snort-config directory!"
    exit
fi

WORK_DIR=$PWD/snortrules
ARCHIVE=snortrules.tar.gz

rm -rf $WORK_DIR
mkdir -p $WORK_DIR

cd $WORK_DIR
##
## Download latest
##
echo 
echo "Downloading"
echo 
wget \
 --no-check-certificate \
 https://ids.untangle.com/$ARCHIVE

##
## Untar to work directory
##
echo
echo "Unarchiving"
echo
tar -xzf $ARCHIVE

##
## Copy templates from current
##
echo
echo "Copying templates"
echo

if [ ! -d templates ] ; then
    mkdir templates
else
    rm -f templates/*
fi
cp ../files/usr/share/untangle-snort-config/current/templates/* templates

##
## Removing unused binaries
##
echo
echo "Removing unused binaries"
echo
for f in `ls $WORK_DIR/so_rules/precompiled`
do
    if [[ "$f" != *"Debian"* ]]
    then
        rm -rf $WORK_DIR/so_rules/precompiled/$f
    fi
done

##
## repackage
##
echo
echo "Repackaging"
echo 
rm -f $ARCHIVE
tar -czf $ARCHIVE *

##
## Move to repository
##
echo
echo "Copying"
echo 
cp -a $ARCHIVE ../files/usr/share/untangle-snort-config/
rm -f $ARCHIVE

##
## Remove work
##
cd -
#rm -rf $WORK_DIR
