.\" wing requests are required for all man pages.
.TH gocr 1 "Sun Sep  3 14:59:19 CEST 2000" "" "Gnu Optical Character Recognition"
.SH NAME
gocr - Gnu Optical Character Recognition
.SH SYNOPSIS
.B gocr 
.RB [options] 
.IR pnm_file_name
.SH OPTIONS
.TP
.B \-h 
get this help
.TP
.BI \-i\  name
input image file (pnm,pgm,pbm,ppm,pcx,...)
.TP
.BI \-i\ \-
read PNM from stdin (djpeg -gray a.jpg | gocr -)
.TP
.BI \-o\  name
output file  (redirection of stdout)
.TP
.BI \-e\  name
logging file (redirection of stderr)
.TP
.BI \-l\  num
grey level 0<160<=255
.TP
.BI \-d\  num
dust_size (remove all smaller clusters, 10=default)
.TP
.BI \-s\  num
spacewidth/dots (0 = autodetect)
.TP
.BI \-v\  num
verbose  [summed]
      1      print more info
      2      list chapes  of boxes (see -c)
      4      list pattern of boxes (see -c)
      8      print pattern after recognition
     16      print line infos
     32      debug outXX.pgm
.TP
.BI \-c\  string
list of chars (_ = not recognized chars)
.TP
.BI \-m\  num
operation modes, ~ = switch off
      2      use database (early development)
      4      layout analysis, zoning (development)
      8      ~ compare non recognized chars
     16      ~ divide overlapping chars
     32      ~ context correction
     64      char packing (development)
.TP
.B \-n 
1      only numbers

.SH DESCRIPTION

.B What is it?
.TP
OCR = optical character recognition
.TP
read pnm, pbm, pgm, ppm, some pcx and tga image files (or PNM from stdin)
.TP
if pnm-tools installed and running linux-like system you can also use  pnm.gz, pnm.bz2, png, jpg, tiff, gif, bmp (see pnm.cc for full list)
.TP
output of text

.TP
.B How to start? (QUICK START)
.TP
gocr -h
help
.TP
gocr file.pbm
minimum options
.TP
gocr -v 1 file.pbm >out.txt 2>out.log
generate text- and log file
.\" djpeg -pnm -gray text.jpg | gocr -    # using JPEG-files
.TP
gzip -cd text.pbm.gz | gocr -
using gzipped PBM-files
.\"  giftopnm text.gif | gocr -            # using GIF-files
.TP
gocr -v 1 -v 32 -m 4 file.pbm
zoning and out30.bmp output
.\"  xli -geometry 400x400 out30.bmp # see details using xli (recommanded viewer)
.TP
wish gocr.tcl
X11-tcl/tk-frontend (development version)



.SH EXAMPLES
There is some examples in /usr/share/doc/gocr

Try to something like:
.TP
.B gocr -i file.pbm -o file.txt -e file.log -v X -m Y
.TP
where X and Y are the sum of values you want. i.e.:
.B -v 15 
.B -m 24

.\" This next request is for sections 1, 6, 7 & 8 only
.\"     (command return values (to shell) and
.\"       fprintf/stderr type diagnostics)
.\" .Sh DIAGNOSTICS
.\" The next request is for sections 2 and 3 error
.\" and signal handling only.
.\" .Sh ERRORS
.\" .Sh SEE ALSO
.\" .Sh STANDARDS
.\" .Sh HISTORY
.SH SEE ALSO
gocr.tcl(1) gtk-ocr(1)
.SH AUTHORS
Joerg.Schulenburg@physik.uni-magdeburg.de,
jschulen@gmx.de
.SH BUGS
Send any bug to the Debian Bug Tracking System.

