.\" wing requests are required for all man pages.
.TH gtk-ocr 1 "Sun Sep  3 14:59:19 CEST 2000" "" "Graphical frontend to untangle-gocr"
.SH NAME
gtk-ocr - Graphical frontend to untangle-gocr
.SH SYNOPSIS
.B gtk-ocr
.SH DESCRIPTION

.B What is it?
.TP
OCR = optical character recognition
.TP
read pnm, pbm, pgm, ppm, some pcx and tga image files (or PNM from stdin)
.TP
if pnm-tools installed and running linux-like system you can also use  pnm.gz, pnm.bz2, png, jpg, tiff, gif, bmp (see pnm.cc for full list)
.TP
output of text

.SH EXAMPLES
There is some examples in /urs/share/doc/untangle-gocr

.SH SEE ALSO
untangle-gocr(1) goct.tlc(1)
.\" .Sh STANDARDS
.\" .Sh HISTORY
.SH AUTHORS
Joerg.Schulenburg@physik.uni-magdeburg.de,
jschulen@gmx.de
.SH BUGS
Send any bug to the Debian Bug Tracking System.
