#!/bin/sh

# Use intel on jetway boxes
if ! grep -qE 'jetway' /etc/initramfs-tools/modules ; then
    cat <<EOF > /etc/initramfs-tools/modules
# Untangle jetway bootsplash settings
intel_agp
drm
i915 modeset=1
EOF
    dpkg-trigger --no-await update-initramfs
fi

exit 0
