#!/bin/bash

if [ "$1" = "configure" ] ; then
  # oldVersion will be non-empty if untangle-linux-config has been
  # configured before
  oldVersion="$2" 
fi

ourInit() {
if [ -x /usr/sbin/invoke-rc.d ] && [ ! "`readlink /usr/sbin/invoke-rc.d`" = /bin/true ] ; then
  invoke-rc.d $1 $2
else
  /etc/init.d/$1 $2
fi
}

grabRootDevice() {
  awk '/^[^#].*[ \t]+\/[ \t]+/ {print $1}' $1
}
 
# Clean up stuff left around by old version
rm -f /boot/vmlinuz-ut
rm -f /boot/vmlinuz
rm -f /boot/initrd.img

kernelRoot=$(perl -ne 'print $1 if m|root=([^\s]+)|' /proc/cmdline)

if [ -n "$kernelRoot" ]; then
  # regular boot; the system apparently was fine with whatever got
  # passed to the kernel by grub, so we'll use that too
  root=$kernelRoot
elif [ -f /etc/mtab ]; then
  root=$(grabRootDevice /etc/mtab)
fi

# If we couldn't find a root, don't bother with the rest as we must
# be in some fake install time.
[ -z "$root" ] && exit 0

case "$root" in
  /dev/*) # let's get a UUID for this device
    rootdev=$(blkid $root | awk '{gsub(/"/, "", $2) ; print $2}') ;;
  *) # fallback: we already have a UUID
    rootdev="$root" ;;
esac

menuLst="/boot/grub/menu.lst"
menuLstPreUntangle="${menuLst}-pre-untangle"

# rewrite fstab
echo "Forcing / in fstab to map to current root device ($rootdev)"
perl -i -pe 's|^[^\s#]+(\s+/\s+)|'$rootdev'$1|' /etc/fstab

# Re-create menu.lst
echo "Installing Untangle $menuLst"
mkdir -p /boot/grub

if [[ $(cat /etc/debian_version) == 6* ]] ; then
  menuFile="/usr/share/untangle-linux-config/menu-squeeze.lst"
else
  echo "UNSUPPORTED DEBIAN VERSION: `cat /etc/debian_version`"
  menuFile="/usr/share/untangle-linux-config/menu-squeeze.lst"
fi

sed -e "s/@ROOTDEV@/$rootdev/" $menuFile > $menuLst

[ -f $menuLstPreUntangle ] || cp $menuLst $menuLstPreUntangle

currentDefault=$(head -1 /boot/grub/default 2>/dev/null | perl -pe 's/^(\d).*/$1/')
if [ -z "$currentDefault" ] || [ "$currentDefault" = "default" ] ; then
    echo "Setting default grub option: 0"
    /usr/sbin/grub-set-default 0
fi

# Reset default (not necessary now, necessary when upgrading kernel)
# currentKernelParams="$(grep -E '^kernel' $menuLst | head -$((1 + $currentDefault)) | tail -1)"
# case "$currentKernelParams" in
#   *force-video-safe*|"") newDefault=1 ;;
#   *noapic*) newDefault=3 ;;
#   *) newDefault=0 ;;
# esac
# /usr/sbin/grub-set-default $newDefault

echo "Updating grub..."
/usr/sbin/update-grub

# disable bootlog (conflicts with plymouth and enabled by default in squeeze)
# bug #11162
sed -e 's/BOOTLOGD_ENABLE.*/BOOTLOGD_ENABLE=No/' -i /etc/default/bootlogd

exit 0
