#!/bin/bash

if [ "$1" = "configure" ] ; then
  # oldVersion will be non-empty if untangle-linux-config has been
  # configured before
  oldVersion="$2" 
fi

ourInit() {
if [ -x /usr/sbin/invoke-rc.d ] && [ ! "`readlink /usr/sbin/invoke-rc.d`" = /bin/true ] ; then
  invoke-rc.d $1 $2
else
  /etc/init.d/$1 $2
fi
}

grabRootDevice() {
  awk '/^[^#].*[ \t]+\/[ \t]+/ {print $1}' $1
}
 
# Clean up stuff left around by old version
rm -f /boot/vmlinuz-ut
rm -f /boot/vmlinuz
rm -f /boot/initrd.img

if [ -f /etc/fstab ]; then
  root=$(grabRootDevice /etc/fstab)
elif [ -f /etc/mtab ]; then
  root=$(grabRootDevice /etc/mtab)
fi

# If we couldn't find a root, don't bother with the rest as we must
# be in some fake install time.
[ -z "$root" ] && exit 0

case "$root" in
  /dev/*)
    rootdev=$(blkid $root | awk '{gsub(/"/, "", $2) ; print $2}') ;;
  *) # Fallback
    rootdev="$root" ;;
esac

menuLst="/boot/grub/menu.lst"
menuLstPreUntangle="${menuLst}-pre-untangle"

# Re-create menu.lst
echo "Installing Untangle $menuLst"
mkdir -p /boot/grub
currentDefault=$(head -1 /boot/grub/default | perl -pe 's/^(\d).*/$1/')
if [ -z "$currentDefault" ] || [ "$currentDefault" = "default" ] ; then
  currentDefault=0
fi

[ -f $menuLstPreUntangle ] || cp $menuLst $menuLstPreUntangle
currentKernelParams="$(grep -E '^kernel' $menuLst | head -$((1 + $currentDefault)) | tail -1)"
case "$currentKernelParams" in
  *ut-video*|"") newDefault=0 ;;
  *noapic*) newDefault=2 ;;
  *ut-restore*) newDefault=3 ;;
  *) newDefault=1 ;;
esac

if [[ $(cat /etc/debian_version) == 6* ]] ; then
  menuFile="/usr/share/untangle-linux-config/menu-squeeze.lst"
else
  menuFile="/usr/share/untangle-linux-config/menu.lst"
fi
sed -e "s/@ROOTDEV@/$rootdev/" $menuFile > $menuLst
/usr/sbin/grub-set-default $newDefault
/usr/sbin/update-grub

exit 0
