#!/bin/bash

# might be empty, but it doesn't matter (see examples below)
oldVersion=$2

# One of the main purposes of this package is to reboot the Untangle
# Server when a new kernel is installed.  Thus this package should
# only be revved when you want a reboot.  Starting with 5.4, we're
# making an exception to this rule: we know for a fact that our kernel
# hasn't changed from 5.3 to 5.4, so we will reboot only those people
# that were running something lesser than 5.3~; that way 5\.[34]\.\d.*
# installs won't be rebooted:
#   $ dpkg --compare-versions 5.4.0~svn le 5.3~ && echo reboot
#   $ dpkg --compare-versions 5.3.0~svn le 5.3~ && echo reboot
#   $ dpkg --compare-versions 5.3.3~svn le 5.3~ && echo reboot
#   $ dpkg --compare-versions 5.2.0~svn le 5.3~ && echo reboot
#   reboot
#   $ dpkg --compare-versions 5.2.0 le 5.3~ && echo reboot
#   reboot
#   $ dpkg --compare-versions 5.2 le 5.3~ && echo reboot
#   reboot
#   $ dpkg --compare-versions "" le 5.3~ && echo reboot
#   reboot
if [ -x /etc/init.d/untangle-vm ] && dpkg --compare-versions "$oldVersion" le 5.3~ ; then
    # Bug 5554 -- hotfix the init.d script so it doesn't kill the upgrade
    sed -i -e "s/ grep java | grep uvm/ fgrep java | fgrep com.untangle.uvm.engine.Main/" /etc/init.d/untangle-vm
    uvm-restart reboot
fi

exit 0
