#! /bin/sh

### BEGIN INIT INFO
# Provides:          untangle-development-kernel
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     S
# Default-Stop:      
### END INIT INFO

# Author: Sebastien Delafond <seb@untangle.com>

. /lib/lsb/init-functions

DESC="Untangle LXC client"

start() {
  log_daemon_msg "Starting $DESC"
  log_progress_msg "untangle-development-kernel"    

  /usr/share/untangle-development-kernel/bin/untangle-lxc-running
  if [ $? = 0 ] ; then
      log_failure_msg "Already running"
      exit 1
  fi

  /usr/share/untangle-development-kernel/bin/untangle-lxc-start >/dev/null 2>&1
  RET=$?
  log_end_msg $RET
  [ $RET = 0 ] || exit $RET
}

stop() {
  log_daemon_msg "Stopping $DESC"
  log_progress_msg "untangle-development-kernel"    

  /usr/share/untangle-development-kernel/bin/untangle-lxc-running
  if [ $? != 0 ] ; then
      log_failure_msg "Not running"
      return
  fi

  /usr/share/untangle-development-kernel/bin/untangle-lxc-stop >/dev/null 2>&1
  RET=$?
  log_end_msg $RET
  [ $RET = 0 ] || exit $RET
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    reload|restart|force-reload)
        stop
        start
        ;;
    *)
        /bin/echo "Usage: $0 {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
