const CONFIG_TYPE = {
  AUTO_DHCP: 'AUTO',
  STATIC: 'STATIC',
  PPPOE: 'PPPOE',
  SLAAC: 'SLAAC',
  ASSIGN: 'ASSIGN',
  DISABLED: 'DISABLED',
  ADDRESSED: 'ADDRESSED',
  BRIDGED: 'BRIDGED',
  RELAY: 'RELAY',
  SERVER: 'SERVER',
  AUTO: 'AUTO',
}

const MTU_VALUES = {
  DEFAULT: 1500,
  MIN: 68,
  MAX: 65535,
}

export { CONFIG_TYPE, MTU_VALUES }
