#! /bin/bash

for nic in eth1 eth2 ; do
  hostapdConf="/etc/hostapd/hostapd.conf-$nic"
  if [ -f $hostapdConf ] ; then
    action=start
  else
    action=stop
  fi
  brcm-wifi $action $nic $hostapdConf
done

exit 0
