#! /bin/bash

for nic in eth1 eth2 ; do
  # first we stop any potentially running APs
  brcm-wifi $nic stop

  hostapdConf="/etc/hostapd/hostapd.conf-$nic"
  [ -f $hostapdConf ] && brcm-wifi $nic start $hostapdConf
done

exit 0
