class OSLibrary::Debian::DdclientManager < OSLibrary::DdclientManager
  include Singleton

  ConfigFile = "/etc/ddclient.conf"

  ConfigDaemon = "daemon"
  ConfigProtocol = "protocol"
  ConfigLogin = "login"
  ConfigPassword = "password"
  ConfigServer = "server"

  def register_hooks
    os["network_manager"].register_hook( -100, "ddclient_manager", "write_files", :hook_commit )
  end
  
  def hook_commit
    settings = DdclientSettings.find( :first )
    return if ( settings.nil? )
    
    cfg = []
    
    if ( settings.enabled ) 
      [[ ConfigDaemon, settings.daemon ],
        [ ConfigProtocol, settings.protocol ],
        [ ConfigLogin, settings.login ],
        [ ConfigPassword, settings.password ],
        [ ConfigServer, settings.server + ' ' +settings.hostname ]].each do |var,val|
        next if ( val.nil? || val == "null" )
        cfg << "#{var}=\"#{val}\""
      end
    end
    
    next if cfg.size == 0
    
    file_name = "#{ConfigFile}"
    
    os["override_manager"].write_file( file_name, header, "\n", cfg.join( "\n" ), "\n" )
    
    #Kernel.system( "hostname #{settings.hostname}" )
  end
  
  def header
    <<EOF
## #{Time.new}
## Auto Generated by the Untangle Net Alpaca
## If you modify this file manually, your changes
## may be overriden
EOF
  end
end
