class OSLibrary::Debian::DnsServerManager < OSLibrary::DnsServerManager
  include Singleton

  ResolvConfFile = "/etc/resolv.conf"
  DnsMasqLeases = "/var/lib/misc/dnsmasq.leases"

  def register_hooks
    os["network_manager"].register_hook( -200, "dns_server_manager", "write_files", :hook_commit )
  end

  def hook_commit
    resolv_conf
  end

  ## Sample entry
  ## 1193908192 00:0e:0c:a0:dc:a9 10.0.0.112 gobbleswin 01:00:0e:0c:a0:dc:a9
  def dynamic_entries
    entries = []
    ## Open up the dns-masq leases file and print create a table for each entry
    File.open( DnsMasqLeases ) do |f|
      f.each_line do |line|
        expiration, mac_address, ip_address, hostname, client_id = line.split( " " )
        next if ( hostname.nil? || hostname == "*" )
        entries << DynamicEntry.new( ip_address, hostname )
      end
    end
    entries.sort!
    entries

  end

  private

  def resolv_conf
    name_servers = []
    Interface.find_all( :wan => true, :config_type => InterfaceHelper::ConfigType::STATIC ).each do |i|
      config = i.current_config

      next if config.nil?
      name_servers << config.dns_1
      name_servers << config.dns_2
    end

    ## Delete all of the empty name servers, and fix the lines.
    name_servers = name_servers.delete_if { |ns| ns.nil? || ns.empty? }.map { |ns| "nameserver #{ns}" }

    ## REVIEW: Need to get the search domain.

    ## REVIEW: This is a possible hook where something else would introduce or replace name servers.
    
    header = <<EOF
## #{Time.new}
## Auto Generated by the Untangle Net Alpaca
## If you modify this file manually, your changes
## may be overriden
EOF

    os["override_manager"].write_file( ResolvConfFile, header, name_servers.join( "\n" ), "\n" )
  end
end

