#
# $HeadURL$
# Copyright (c) 2007-2008 Untangle, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License, version 2,
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# AS-IS and WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE, TITLE, or
# NONINFRINGEMENT.  See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
class OSLibrary::Debian::OverrideManager < OSLibrary::OverrideManager
  include Singleton

  SysCtlConfigFile = "/etc/untangle-net-alpaca/sysctl"

  def register_hooks
    ## The network manager only needs to write the file, because update address will
    ## automatically update run the script.
    os["network_manager"].register_hook( 200, "override_manager", "write_files", :hook_write_files )
  end

  def hook_commit
    write_files
    update_sysctl
  end

  def hook_write_files
    
    alpaca_settings = AlpacaSettings.find( :first )
    alpaca_settings = AlpacaSettings.new( :send_icmp_redirects => true ) if alpaca_settings.nil?

    sysctl_text = header
    
    sysctl_text += <<EOF
sysctl -q -w net.ipv4.ip_forward=1

find /proc/sys/net/ipv4/conf -type f -name 'send_redirects' | while read f ; do
  echo #{alpaca_settings.send_icmp_redirects} > ${f}
done
EOF

    write_executable( SysCtlConfigFile, sysctl_text, "\n" )
  end

  def hook_update_sysctl
    run_command( SysCtlConfigFile ) if File.executable?( SysCtlConfigFile )
  end

  def header
    <<EOF
#!/bin/dash

## #{Time.new}
## Auto Generated by the Untangle Net Alpaca
## If you modify this file manually, your changes
## may be overriden
EOF
  end
end
