#!/bin/sh

NAT_CACHE_DEB="/var/lib/mvvm/nat-transform.deb"

. /etc/default/mvvm

# restore database
dropdb -U postgres mvvm

createuser -U postgres -d -A metavize 2>/dev/null
createuser -U postgres -d -A untangle 2>/dev/null
createdb -O postgres -U postgres mvvm
/usr/share/untangle/bin/update-schema settings mvvm
/usr/share/untangle/bin/update-schema events mvvm
/usr/share/untangle/bin/update-schema settings nat-transform
/usr/share/untangle/bin/update-schema events nat-transform
psql -X -U postgres mvvm <<EOF
INSERT INTO tid VALUES (1);
INSERT INTO transform_manager_state VALUES (nextval('hibernate_sequence'), 2);
INSERT INTO transform_persistent_state VALUES (nextval('hibernate_sequence'), 'nat-transform', 1, '\\\\001\\\\000', 'running');
INSERT INTO transform_preferences VALUES (nextval('hibernate_sequence'), 1, 255, 175, 175, 255);
INSERT INTO tid VALUES (2);
INSERT INTO transform_persistent_state VALUES (nextval('hibernate_sequence'), 'ftp-casing', 2, '\\\\002\\\\000', 'running');
INSERT INTO transform_preferences VALUES (nextval('hibernate_sequence'), 2, 255, 175, 175, 255);
INSERT INTO tr_nat_settings VALUES (nextval('hibernate_sequence'), 1, 0, true, null, null, false, null, true, null, null, 0, true, null, false);
EOF

# remove files
rm -f /usr/share/metavize/conf/networking.sh
rm -f /usr/share/metavize/conf/timezone
rm -f /usr/share/metavize/conf/keystore
# need to preserve the key (bug #2510)
mv -f $ACTIVATION_KEY_FILE $ACTIVATION_KEY_FILE_TMP
rm -rf /usr/share/metavize/conf/openvpn
rm -rf /usr/share/metavize/quarantine
rm -rf /etc/openvpn

# restore initial LDAP db
/etc/init.d/slapd stop
rm -rf /var/lib/ldap
mkdir /var/lib/ldap
cp /usr/share/metavize/conf/ldap.DB_CONFIG /var/lib/ldap/DB_CONFIG
slapadd -l /usr/share/metavize/conf/initial.ldif
slapindex
/etc/init.d/slapd start

# restore canonical files
(cd / && tar zvxf /usr/share/metavize/conf/canonical.tar.gz)

# restore factory root pw
echo "root:YKN4WuGxhHpIw" | /usr/sbin/chpasswd -e

## restore the NAT transform if necessary
if [ -f ${NAT_CACHE_DEB} ]; then
    dpkg -l untangle-node-router | grep '^ii' > /dev/null || dpkg -i ${NAT_CACHE_DEB}
fi
