#! /bin/bash

MAX_SPARE=1

# The tuning depends on the memory available. We have settings for > 1 gig, and <= 1 gig

echo "  Customizing HW-related settings for clamav"

MEM=$(awk '/MemTotal/ { print $2 }' < /proc/meminfo)
if [ $MEM -gt 1100000 ] ; then
    # enable extra signatures
    echo "  Enabling extra signatures"
    sed -i "s/^user_configuration_complete=.*/user_configuration_complete=\"yes\"/" /etc/clamav/clamav-unofficial-sigs.conf
else
    echo "  Disabling extra signatures"
    # disable extra signatures
    sed -i "s/^user_configuration_complete=.*/user_configuration_complete=\"no\"/" /etc/clamav/clamav-unofficial-sigs.conf
    # remove existing signatures
    rm -f /var/lib/clamav/honeynet*
    rm -f /var/lib/clamav/junk*
    rm -f /var/lib/clamav/jurlbl*
    rm -f /var/lib/clamav/mbl*
    rm -f /var/lib/clamav/phish*
    rm -f /var/lib/clamav/rogue*
    rm -f /var/lib/clamav/sanesecurity*
    rm -f /var/lib/clamav/scam*
    rm -f /var/lib/clamav/securiteinfo*
    rm -f /var/lib/clamav/spamimg*
    rm -f /var/lib/clamav/winnow*
fi

