#!/bin/sh
#
# 3iptables-ppp_up-rules, v0.6 03/09/2003.
# Kiryanov Vasiliy, mailto://root@lycos.ru
#
# this script run when PPP down and
# restore iptables RULES that exist before PPP up

# If you find some errors or missing write me: root@lycos.ru
#--------------------------------------------------------------

# restoring iptables RULES
/sbin/iptables-restore < /tmp/3iptables-ppp_up-SAVE

#unlink(remove) temp file
rm -f /tmp/3iptables-ppp_up-SAVE 

#
# try '# ifconfig' to see if your ppp interface all right
# try '# iptables --list --verbose' to see if all rules right 
