#! /bin/bash

getKeyFingerprint() {
  gpg $1 | awk '/pub/ {gsub(/.*\//, "", $2) ; print $2}'
}

# attempt to fetch the GPG keys anyway
. /usr/share/untangle-spamassassin-update/sa-fetch-keys.sh

# SARE fingerprint
SARE_FINGERPRINT=`getKeyFingerprint ${SARE_GPG_KEY}`

# SOUGHT fingerprint
SOUGHT_FINGERPRINT=`getKeyFingerprint ${SOUGHT_GPG_KEY}`

needToRestart="false"

if [ -x /usr/bin/sa-update ]; then
    /usr/bin/sa-update --channelfile ${GPG_KEYS_DIR}/sa-update-channels.txt --gpgkey $SARE_FINGERPRINT > /dev/null 2>&1
    [ $? = 0 ] && needToRestart="true"
    /usr/bin/sa-update --channel sought.rules.yerp.org --gpgkey $SOUGHT_FINGERPRINT > /dev/null 2>&1
    [ $? = 0 ] && needToRestart="true"
fi

# restart spamassassin if needed
[ $needToRestart = "true" ] && /etc/init.d/spamassassin restart &> /dev/null &

# sa-update exits with a status to tell us if an update happened.
# don't pass this up to cron.
exit 0
