#! /bin/bash

# attempt to fetch the GPG keys anyway
/usr/share/untangle-spamassassin/sa-fetch-keys.sh

if [ -x /usr/bin/sa-update ]; then
    /usr/bin/sa-update --channelfile /usr/share/untangle-spamassassin-update/sa-update-channels.txt --gpgkey 856AA88A
fi

# restart spamassassin
/etc/init.d/spamassassin restart &> /dev/null &

# sa-update exits with a status to tell us if an update happened.
# don't pass this up to cron.
exit 0
