#!/bin/bash

# 12.0 conversion for new names (apache 2.4.3)
if [ -h /etc/apache2/sites-available/uvm.conf ]; then
    rm -f /etc/apache2/sites-available/uvm.conf
fi
# 12.0 conversion for new names (apache 2.4.3)
if [ -f /etc/apache2/sites-available/uvm ]; then
    mv /etc/apache2/sites-available/uvm /etc/apache2/sites-available/uvm.conf
    rm -f /etc/apache2/sites-available/uvm
    rm -f /etc/apache2/sites-enabled/uvm
fi

if [ -f /etc/apache2/untangle-conf.d ]; then
    t=$(mktemp)
    mv /etc/apache2/untangle-conf.d $t
    mkdir -p /etc/apache2/untangle-conf.d
    mv $t /etc/apache2/untangle-conf.d/uvm.conf
fi

true
