#!/usr/bin/ruby

ARGV.each{ |file| 
  next if !File::exists?( file )
  f = File::open( file )
  data = f.readlines
  m = /#!.*ruby(.*)/.match( data[0])
  next if !m or m[0][0..14] == '#!/usr/bin/ruby'
  f.close
  f.reopen( file, 'w' )
  rargs = ''
  rargs = m[1] if m and m[1]
  f.write( "#!/usr/bin/ruby#{rargs}\n\n" )
  f.write( data )
}
