#!/bin/sh

ourInit() {
if [ -x /usr/sbin/invoke-rc.d ] && [ ! "`readlink /usr/sbin/invoke-rc.d`" = /bin/true ] ; then
  invoke-rc.d $1 $2
else
  /etc/init.d/$1 $2
fi
}

if [ -x "/etc/init.d/untangle-firmware-common" ]; then
  ourInit untangle-firmware-common restart
fi

rm -f /usr/share/untangle-snort-config/snortrules.tar.gz
rm -f /usr/share/untangle-snort-config/current/rules/emerging-deleted.rules
rm -f /usr/share/untangle-snort-config/current/rules/emerging-current_events.rules
rm -f /usr/share/untangle-snort-config/current/rules/emerging-activex.rules

exit 0

