#! /bin/bash

ourInit() {
if [ -x /usr/sbin/invoke-rc.d ] && [ ! "`readlink /usr/sbin/invoke-rc.d`" = /bin/true ] ; then
  invoke-rc.d $1 $2
else
  /etc/init.d/$1 $2
fi
}

FDIR=/usr/share/untangle-fuzzyocr

# copy in config files
cp -p $FDIR/FuzzyOcr.cf /etc/mail/spamassassin
cp -p $FDIR/FuzzyOcr.pm /usr/share/perl5/Mail/SpamAssassin/Plugin/

# setting of pre314 var moved to spamc-mv.postinst

# reload SA
/etc/init.d/spamassassin reload

exit 0
