#! /bin/bash

ourInit() {
if [ -x /usr/sbin/invoke-rc.d ] && [ ! "`readlink /usr/sbin/invoke-rc.d`" = /bin/true ] ; then
  invoke-rc.d $1 $2
else
  /etc/init.d/$1 $2
fi
}

rm -f /etc/mail/spamassassin/FuzzyOcr.*
rm -f /usr/share/perl5/Mail/SpamAssassin/Plugin/FuzzyOcr.pm

# reload SA
ourInit spamassassin reload

exit 0
