#!/bin/bash
#
# Temporary until we have connection to uvm working. XXX
#

if [ $# -ne 2 -o "$1" != "--openfiler" -o "$2" != "--kickstart" ]; then
    echo "Segmentation fault."
    exit 1
fi

# enable cache
echo "NO"

# YES
echo "YES"

# enable hesiod 2
echo "NO"

# hesiod lhs
echo ""

# hesiod rhs 4
echo ""

# enable ldap XXX
echo "YES"

# enable ldaps XX (applies locally or both?) 6
echo "NO"

# ldap server
echo "localhost:3899"

# ldap base dn 8
echo "dc=nodomain"

# enable nis 
echo "NO"

# nis server 10
echo ""

# nis domain
echo ""

# local policies (pam_stack, deprecated in recent versions) 12
echo "YES"

# enable shadow
echo "YES"

# enable md5 14
echo "YES"

# enable kerberos == use kerberos for system auth (like kerberos at untangle!, not ad)
echo "NO"

# kerberos realm  16
echo "EXAMPLE.COM"

# kerberos kdc
echo ""

# kerberos admin server 18
echo ""

# enable ldap auth
echo "NO"

# enable ldaps (again) 20
echo "NO"

# ldap server (again)
echo "localhost:3899"

# ldap base dn (again) 22
echo "dc=nodomain"

# enable smb (auth) Unused XX
echo "NO"

# smb workgroup XXX 24
echo "untangle"

# smb servers XXX (winbindcontrollers)
echo "10.0.0.41"

# enable compat Unused XX 26
echo "NO"

# enable db Unused XX
echo "NO"

# enable nis3 28
echo "NO"

# enable winbind XXX
echo "YES"

# enable wins 30
echo "NO"

# kerberos kdc via dns Unused XX
echo "NO"

# smb realm XXX 32
echo "UNTANGLE.LOCAL"

# smb security XXX
echo "ads"

# smb idmap uid 34
echo "16777216-33554431"

# smb idmap gid
echo "16777216-33554431"

# winbind template shell 36
echo "/sbin/nologin"

# ldap bind dn XX (authenticated bind dn)??
echo ""

# ldap bind pw XX (authenticated bind pw)?? 38
echo ""

# ldap root bind dn
echo "cn=admin"

# ldap root bind pw 40
echo "nimda11lacol"

exit 0
