#!/bin/bash
#
# Temporary until we have connection to uvm working. XXX
#

if [ $# -ne 2 -o "$1" != "--openfiler" -o "$2" != "--kickstart" ]; then
    echo "Segmentation fault."
    exit 1
fi

# enable cache
echo "NO"

# YES
echo "YES"

# enable hesiod 2
echo "NO"

# hesiod lhs
echo ""

# hesiod rhs 4
echo ""

# enable ldap
echo "YES"

# enable ldaps XX (applies locally or both?) 6
echo "NO"

# ldap server
echo "localhost:3899"

# ldap base dn 8
echo "dc=nodomain"

# enable nis 
echo "NO"

# nis server 10
echo ""

# nis domain
echo ""

# local policies (pam_stack, deprecated in recent versions) 12
echo "YES"

# enable shadow
echo "YES"

# enable md5 14
echo "YES"

# enable kerberos XXX
echo "NO"

# kerberos realm XXX 16
echo "EXAMPLE.COM"

# kerberos kdc XXX
echo ""

# kerberos admin server XXX 18
echo ""

# enable ldap auth
echo "NO"

# enable ldaps (again) 20
echo "NO"

# ldap server (again)
echo "localhost:3899"

# ldap base dn (again) 22
echo "dc=nodomain"

# enable smb (auth) XXX ???
echo "NO"

# smb workgroup XXX 24
echo "untangle"

# smb servers XXX (winbindcontrollers)
echo "email.untangle.com"

# enable compat XXX unused??? 26
echo "NO"

# enable db XXX ???
echo "NO"

# enable nis3 28
echo "NO"

# enable winbind
echo "YES" XXX

# enable wins 30
echo "NO"

# kerberos kdc via dns  XXX ???
echo "NO"

# smb realm XXX 32
echo "UNTANGLE.LOCAL"

# smb security XXX
echo "ads"

# smb idmap uid 34
echo "16777216-33554431"

# smb idmap gid
echo "16777216-33554431"

# winbind template shell 36
echo "/sbin/nologin"

# ldap bind dn XXX ??
echo ""

# ldap bind pw XXX ?? 38
echo ""

# ldap root bind dn
echo "cn=admin"

# ldap root bind pw 40
echo "nimda11lacol"

exit 0
