#!/bin/bash
#
# Debian "replacement" for 'service foo status'.  Only works for services known
# to be used in NAS.
#

if [ $# -ne 1 ]; then
    echo "usage: service-status servicename"
    exit 1
fi

daemonname=

case "$1" in
    winbind)
	daemonname=winbindd
	;;
    samba)
	daemonname=smbd
	;;
    nfs-kernel-server)
	daemonname=nfsd
	;;
    nfs-kernel-server)
	daemonname=nfsd
	;;
    proftpd)
	daemonname=proftpd
	;;
    open-iscsi)
	daemonname=iscsid
	;;
    iscsitarget)
	daemonname=ietd
	;;
    rsync)
        # Needs special handling since client and server have same name.
	if ps ax | fgrep rsync | fgrep -q -e --daemon; then
	    echo "rsync is running"
	else
	    echo "rsync is stopped"
	fi
	exit 0
	;;
    acpid)
	daemonname=acpid
	;;
    httpd)
	# This is easier than querying the UVM.  We might restart apache without needing
	# to, but that has little effect.  XXX
	echo "httpd is running"
	exit 0
	;;
    *)
	echo "service $1 not found"
	exit 2
esac

if pidof $daemonname > /dev/null; then
    echo "$daemonname is running"
else
    echo "$daemonname is stopped"
fi

exit 0
