#! /bin/dash

HOSTAPD_CONF_DIR="/etc/hostapd"
WLAN_CONF="$HOSTAPD_CONF_DIR/hostapd.conf-wlan"
WLAN0_CONF="${WLAN_CONF}0"
WLAN1_CONF="${WLAN_CONF}1"

# backup uvm-generated configurations first
for f in $WLAN0_CONF $WLAN1_CONF ; do
  cp $f ${f}.bak
done

# comment out ht_capab for both interfaces
perl -i -pe 's/^(?=ht_capab)/#/' $WLAN0_CONF $WLAN1_CONF

# change wlan0 mode to "a"
perl -i -pe 's/(?<=hw_mode=).+/a/' $WLAN0_CONF

# change wlan0 channel to 36
perl -i -pe 's/(?<=channel=).+/36/' $WLAN0_CONF

# change wlan1 mode to "g"
perl -i -pe 's/(?<=hw_mode=).+/g/' $WLAN1_CONF
