#! /bin/dash

HOSTAPD_CONF_DIR="/etc/hostapd"
WLAN_CONF="$HOSTAPD_CONF_DIR/hostapd.conf-wlan"
WLAN0_CONF="${WLAN_CONF}0"
WLAN1_CONF="${WLAN_CONF}1"

for f in $WLAN0_CONF $WLAN1_CONF ; do
    if [ -f $f ] ; then
        # backup uvm-generated configurations first
        cp $f ${f}.bak

        # remove unsupported ht_capab
        sed -e 's/\[TX-STBC\]//g' -e 's/\[RX-STBC1\]//g' -e 's/\[DSSS_CCK-40\]//g' -i $f

        # comment out ht_capab for both interfaces
        #perl -i -pe 's/^(?=ht_capab)/#/' $f
    fi
done

