#! /bin/sh

MODEL=$(cat /usr/share/untangle/conf/appliance-model)

if [ ! -f /usr/share/untangle/settings/untangle-vm/network.js ] ; then
  echo "Initializing default network settings for ${MODEL}..."

  ip=$(ip -4 ad show eth1 | awk '/inet/ {gsub(/\/[0-9]+/,"",$2) ; print $2}')
  netmask=$(ifconfig eth1 | awk '/inet addr/ {gsub(/Mask:/,"",$4) ; print $4}')

  mkdir -p /usr/share/untangle/settings/untangle-vm
  cp /usr/share/untangle/conf/appliance-network-config.js /usr/share/untangle/settings/untangle-vm/network.js
  perl -i -pe 's/%ETH1_V4_ADDRESS%/'${ip}'/ ; s/%ETH1_V4_NETMASK%/'${netmask}'/' /usr/share/untangle/settings/untangle-vm/network.js

  # /usr/bin/sync-settings -vv
  echo "Initializing default network settings for ${MODEL}... done"
fi
