class OSLibrary::ArpsManager < Alpaca::OS::ManagerBase
  include Singleton

  ConfigFile = "/etc/untangle-net-alpaca/arps"

  def register_hooks
#    os["network_manager"].register_hook( -100, "arps_manager", "write_files", :hook_commit )
  end
  
  def hook_commit
    static_arps = StaticArp.find( :all )
    
    cfg = []

    static_arps.each do |static_arp|
      #TODO is this the right command? Maybe add pub or temp arguments?
      cfg << "arp -s " + static_arp.hostname + " " + static_arp.hw_addr
    end
    
    os["override_manager"].write_file( ConfigFile, header, "\n", cfg.join( "\n" ), "\n" )
    #Kernel.system( "hostname #{settings.hostname}" )
  end
  
  def header
    <<EOF
#!/bin/bash
## #{Time.new}
## Auto Generated by the Untangle Net Alpaca
## If you modify this file manually, your changes
## may be overriden
EOF
  end
end
