class OSLibrary::PppoeManager < Alpaca::OS::ManagerBase
  include Singleton

  ConnectionNamePrefix = "connection-"
  PeersFilePrefix = "/etc/ppp/peers/" + ConnectionNamePrefix
  PapSecretsFile = "/etc/ppp/pap-secrets"

  def register_hooks
    os["network_manager"].register_hook( -100, "pppoe_manager", "write_files", :hook_commit )
  end
  
  def hook_commit
    settings = IntfPppoe.find( :first )
    if ( settings.nil? )
    end
    
    cfg = []
    secrets = []
   

    cfg << "noipdefault"
    cfg << "hide-password"
    cfg << "noauth"
    cfg << "persist"
    cfg << "defaultroute"
    cfg << "replacedefaultroute"
    if ( settings.use_peer_dns )
      cfg << "usepeerdns"
    end
    
    conditions = [ "wan=?", true ]
    wanInterface = Interface.find( :first, :conditions => conditions )


    cfg << "pid="+PppoePidFile
    cfg << "use=if, if=" + wanInterface.os_name ],

    secrets << "\"" + settings.username + "\" *  \"" + settings.password + "\""   
  
  
    os["override_manager"].write_file( PeersFilePrefix+wanInterface.os_name, header, "\n", cfg.join( "\n" ), "\n" )
    os["override_manager"].write_file( PapSecretsFile, header, "\n", secrets.join( "\n" ), "\n" )
  end
  
  def header
    <<EOF
## #{Time.new}
## Auto Generated by the Untangle Net Alpaca
## If you modify this file manually, your changes
## may be overriden
EOF
  end
end
