class OSLibrary::RoutesManager < Alpaca::OS::ManagerBase
  include Singleton

  ConfigFile = "/etc/untangle-net-alpaca/routes"



  def register_hooks
#    os["network_manager"].register_hook( -100, "routes_manager", "write_files", :hook_commit )
  end
  
  def hook_commit
    network_routes = NetworkRoute.find( :all )
    
    cfg = []

    network_routes.each do |network_route|
          cfg << "route add " + network_route.target + " netmask " + network_route.netmask + " gw " + network_route.gateway + " # " + network_route.name
    end
    
    os["override_manager"].write_file( ConfigFile, header, "\n", cfg.join( "\n" ), "\n" )
    #Kernel.system( "hostname #{settings.hostname}" )
  end
  
  def header
    <<EOF
#!/bin/bash
## #{Time.new}
## Auto Generated by the Untangle Net Alpaca
## If you modify this file manually, your changes
## may be overriden
EOF
  end
end
