#! /bin/bash

# We set the date to 2016-07-01 if not able to set via NTP.
# If before 2016-08-01, then we must have failed to get NTP.
# Try again

now=$(date +%s)
check=$(date -d 2016-08-01 +%s)
if [ $now -lt $check ] ; then
  # start rdate and kill after 300 seconds regardless
  nohup rdate -s time.mit.edu > /dev/null 2>&1 &
  nohup /bin/sh -c "sleep 300 ; pkill -f 'rdate' || true" > /dev/null 2>&1 &

  # start ntpd and kill after 300 seconds regardless
  # nohup ntpd -q -g > /dev/null 2>&1 &
  # nohup /bin/sh -c "sleep 300 ; pkill -f 'ntpd -q' || true" > /dev/null 2>&1 &
fi

