#! /bin/sh

set -e

FLAG_FLASHED="/var/lib/untangle-flashed"
KERNEL_VERSION=$(uname -r)
PART_ONE="/dev/mtdblock2"
PART_TWO="/dev/mtdblock4"

## functions

hashPart() {
  # the 1st 100k is enough for a fingerprint
  dd if=$1 bs=100k count=1 2> /dev/null | md5sum
}

## main

# remove older, unused flag
rm -f $FLAG_FLASHED

# re-flash both partitions if they're not the same
if [[ $(hashPart $PART_ONE) != $(hashPart $PART_TWO) ]] ; then
  for p in $PART_ONE $PART_TWO ; do
    dd if=/boot/vmlinux-${KERNEL_VERSION}.trx of=$p bs=1M 2> /dev/null
  done
fi
