#! /bin/sh

# if loading compat fails, run depmod
modprobe compat
if [ ! $? -eq 0 ] ; then
    depmod -a
fi

# load modules
modprobe compat
modprobe cfg80211
modprobe mac80211
modprobe mwlwifi

# make sure they show up in ifconfig
ifconfig wlan0 up
ifconfig wlan1 up

exit 0
