#! /bin/sh

# load the first module
# if it fails run depmode
modprobe compat
if [ $? != 0 ] ; then
    echo "Running depmod..."
    depmod -a
fi

# if any command fails after this, exit with error
set -e

# load modules
modprobe compat
modprobe cfg80211
modprobe mac80211
modprobe mwlwifi

# make sure they show up in ifconfig
ifconfig wlan0 up
ifconfig wlan1 up

exit 0
