debian/build/untangle-iptables/include/*.h usr/include
debian/build/untangle-iptables/include/lib* usr/include
debian/build/untangle-iptables/libiptc/*.a usr/lib
debian/build/untangle-iptables/libipq/*.a usr/lib
debian/build/untangle-iptables/*.a usr/lib
debian/build/untangle-iptables/libipq/*.3 usr/share/man/man3
debian/build/doc/netfilter-extensions-HOWTO* usr/share/doc/untangle-iptables-dev/html
debian/build/doc/netfilter-hacking-HOWTO* usr/share/doc/untangle-iptables-dev/html
