#! /bin/sh

set -x

if grep -q "TURRIS OMNIA" /usr/share/untangle/conf/appliance-model ; then
  # we don't need to resize anything on the Turris Omnia, as we run
  # from the internal disk and it's already been properly flashed
  exit 0
fi

PART=1 # we work on the 1st partition
FLAG_PART="/var/lib/untangle-resized-part"
FLAG_FS="/var/lib/untangle-resized-fs"

## main

# exit if we've already done the job
[ ! -f $FLAG_FS ] || exit 0


# what device to operate on
disk=${1:-"/dev/sda"}
device=${disk}$PART

if [ ! -f $FLAG_PART ] ; then # no partition resize yet
  # get the start of the PART partition on that device
  start=$(fdisk -l $disk | perl -ne 'if (m|^/|) { s/.*?\s(\d+).*/$1/ ; print }')

  echo "Using fdisk to resize partition..."

  # resize that PART partition so it uses the entire space
  { fdisk $disk <<EOF
p
d
n
p
$PART
$start

p
w
EOF
  }
  echo "Using fdisk to resize partition... done ($?)"

  date -Iseconds > $FLAG_PART

  # tell the scripts to reboot after complete
  touch /tmp/reboot-flag

elif [ ! -f $FLAG_FS ] ; then # partition already resized, let's take care of the FS now

  echo "Launching resize2fs to resize filesystem in background..."

  # resize FS (in the background)
  resize2fs $device &

  # write flag
  date -Iseconds > $FLAG_FS
fi
