#! /bin/bash

function commentOutOption
{
    # first check that it isn't already disabled
    if egrep -q "^\s*$2\s*.*" $1 ; then
        echo "Disabling option $2 in $1"
        # search for line and comment it out
        sed -e "/^\s*$2\s*.*/s/^#*/#/" -i $1
    fi
}

# mount with relatime to minimize writes
mount -o remount,rw,relatime,nodiratime /

# make a new tmpdir
RAMDISK_SIZE="32"
TMPDIR=/tmp

# If ramdisk is not already mounted, create it and initialize database
if [ "tmpfs" != "`stat -f -c '%T' ${TMPDIR}`" ] ; then
    echo "Creating /tmp ramdisk..."
    # mount a ramdisk
    rm -rf ${TMPDIR}
    mkdir -p ${TMPDIR}
    mount -t tmpfs -o size=${RAMDISK_SIZE}m tmpfs ${TMPDIR}
    chmod 0777 ${TMPDIR}
    chmod +t ${TMPDIR}
fi

# link /var/tmp to /tmp
# /var/tmp is traditionally used for tmp files that should presist through a reboot
# sqlite uses /var/tmp during vacuums and despite
# https://www.sqlite.org/tempfiles.html
# setting TMPDIR SQLITE_TMPDIR nor temp_store_directory seems to have no effect
# as such the only fix seems to be just to relink /var/tmp to /tmp
# We check that it isnt already a link to minimize writes on startup
if [ ! -L /var/tmp ] ; then
    echo "Linking /var/tmp to /tmp..."
    rm -rf /var/tmp
    ln -s /tmp /var/tmp
fi

# prevent writes to /var/log/btmp (lastlog and wtmp still written)
chattr +i /var/log/btmp

# Disable apache logging - it logs even with syslog disabled
commentOutOption /etc/apache2/sites-available/uvm.conf CustomLog
commentOutOption /etc/apache2/sites-available/uvm.conf ErrorLog
if ! egrep -q 'ErrorLog.*/dev/null' /etc/apache2/apache2.conf ; then
    echo "Disabling apache logging..."
    sed -e 's|ErrorLog\s*.*|ErrorLog /dev/null|' -i /etc/apache2/apache2.conf
fi

# Disable pyconnector logging
if ! egrep -q '/dev/null' /etc/default/pyconnector ; then
    echo "Disabling pyconnector logging..."
    sed -e 's|^OPTIONS\s*=.*|OPTIONS="-l /dev/null"|' -i /etc/default/pyconnector
fi

# Disable exim logging
# it appears setting log_selector = -all does not work
# so instead just link the log file to /tmp
mkdir -p /tmp/exim
chown Debian-exim:Debian-exim /tmp/exim
if [ ! -L /var/log/exim4 ] ; then
    echo "Linking /var/log/exim4/ to /tmp/exim..."
    rm -rf /var/log/exim4
    ln -s /tmp/exim /var/log/exim4
fi
# Change exit spool dir to tmp dir
if ! egrep -q '^SPOOLDIR\s*=.*/tmp/exim' /etc/exim4/exim4.conf.template ; then
    echo "changing exim spool directory..."
    sed -e 's|^SPOOLDIR\s*=.*|SPOOLDIR = /tmp/exim|' -i /etc/exim4/exim4.conf.template
    /usr/sbin/update-exim4.conf
fi
# Change exim logrotate spool dir to tmp dir
if egrep -q '^\s*rotate 10' /etc/logrotate.d/exim4-base ; then
    echo "changing exim logrotate config..."
    sed -e 's|rotate 10|rotate 1|' -i /etc/logrotate.d/exim4-base
fi
if egrep -q '^\s*rotate 10' /etc/logrotate.d/exim4-paniclog ; then
    echo "changing exim logrotate config..."
    sed -e 's|rotate 10|rotate 1|' -i /etc/logrotate.d/exim4-paniclog
fi

# mv NTP drift file to tmp
# Because the clock is reset on each reboot, there is no point to saving drift on disk
if ! egrep -q 'driftfile /tmp/ntp.drift' /etc/ntp.conf ; then
    echo "Moving ntp drift file to /tmp..."
    sed -e 's|^driftfile\s*.*|driftfile /tmp/ntp.drift|' -i /etc/ntp.conf
fi

# disable moving of lease file
if [ -f /etc/dnsmasq.d/dhcp-leasefile ] ; then
    rm -f /etc/dnsmasq.d/dhcp-leasefile
fi
# move dnsmasq.leases file from /var/lib/misc/dnsmasq.leases to /tmp/dnsmasq.leases
#if [ ! -f /etc/dnsmasq.d/dhcp-leasefile ] ; then
#    echo "Moving dnsmasq lease file to /tmp..."
#    echo "dhcp-leasefile=/tmp/dnsmasq.leases" > /etc/dnsmasq.d/dhcp-leasefile
#fi
#if [ ! -L /var/lib/misc/dnsmasq.leases ] ; then
#    rm -f /var/lib/misc/dnsmasq.leases
#    ln -s /tmp/dnsmasq.leases /var/lib/misc/dnsmasq.leases
#fi

# remove man cron job from daily & weekly to once a month
if [ -f /etc/cron.daily/man-db ] ; then
    mv -f /etc/cron.daily/man-db /etc/cron.monthly/man-db-daily
fi
if [ -f /etc/cron.weekly/man-db ] ; then
    mv -f /etc/cron.weekly/man-db /etc/cron.monthly/man-db-weekly
fi

