#! /bin/sh

set -x

# enable serial console
systemctl --no-block enable serial-getty@ttyS0.service
systemctl --no-block start serial-getty@ttyS0.service
#systemctl --no-block enable getty@ttyS0.service
#systemctl --no-block start getty@ttyS0.service

exit 0
