#!/bin/sh

# this is creates the default network settings for the Linksys wrt1900acs
MODEL=$(perl -pe 's/(.+)/\u\L$1/' /usr/share/untangle/conf/appliance-model)

if [ ! -f /usr/share/untangle/settings/untangle-vm/network.js ] ; then

   echo "Initializing default network settings for ${MODEL}..."

   mkdir -p /usr/share/untangle/settings/untangle-vm
   cp /usr/share/untangle/conf/appliance-network-config.js /usr/share/untangle/settings/untangle-vm/network.js

   /usr/bin/sync-settings.py -vv
   echo "Initializing default network settings for ${MODEL}... done"
fi

