#! /bin/bash

VENDOR=$(awk '{print tolower($1) }' /usr/share/untangle/conf/appliance-model)
RAMDISK_SIZE="32"
DIR=/var/lib/sqlite

# If ramdisk is not already mounted, create it and initialize database
if [ "tmpfs" != "`stat -f -c '%T' ${DIR}`" ] ; then
        # mount a ramdisk
        rm -rf ${DIR}
        mkdir -p ${DIR}
        mount -t tmpfs -o size=${RAMDISK_SIZE}m tmpfs ${DIR}
fi

# 12.2 remove old file
rm -f /etc/cron.hourly/reports-cron-${VENDOR}

