#! /bin/bash

restartService() {
    local t_service=$1

    if [ ! -f /etc/init.d/${t_service} ];  then
        return 0
    fi

    # run this non-blocking in the background
    echo "[DEBUG:`date`] Restarting ${t_service}"
    /etc/init.d/${t_service} restart &
}


restartService spamassassin

# remote support is enabled if sshd us running
pidof sshd && restartService untangle-support-agent

exit 0
