#! /bin/bash

now=$(date +%s)
check=$(date -d 2016-07-01 +%s)
if [ $now -lt $check ] ; then
    date -s "2016-07-01"
fi

# start rdate and kill after 300 seconds regardless
nohup rdate -s time.mit.edu > /dev/null 2>&1 &
nohup /bin/sh -c "sleep 300 ; pkill -f 'rdate' || true" > /dev/null 2>&1 &

# start ntpd and kill after 300 seconds regardless
# nohup ntpd -q -g > /dev/null 2>&1 &
# nohup /bin/sh -c "sleep 300 ; pkill -f 'ntpd -q' || true" > /dev/null 2>&1 &

exit 0
