#!/bin/sh
# Microsoft Azure specific

# If the wizard has not been completed, set the default password to the instance ID
if grep -q "wizardComplete.*false.*" /usr/share/untangle/conf/wizard.js ; then

    # Set the initial admin password to the instance ID
    # FIXME: change this to get some Azure ID instead
    #PASS="`curl -s -q -m 5 http://169.254.169.254/latest/meta-data/instance-id`"
    PASS="passwd"
    if [ $? != 0 ] ; then
        echo -e "\n\nWARNING\n\nFailed to retrieve instance ID\n\n"
    elif [ "$PASS" = "" ] ; then
        echo -e "\n\nWARNING\n\nInvalid instance ID value\n\n"
    else
        /usr/share/untangle/bin/ut-set-admin-passwd.py $PASS
    fi

    # remove this script
    /bin/rm -f $0
fi
