#!/bin/sh
# Microsoft Azure specific

# If the wizard has not been completed, set the default password to
# the instance name
if grep -q "wizardComplete.*false.*" /usr/share/untangle/conf/wizard.js ; then
    # Set the initial admin password to the instance name
    pass=$(curl -H "Metadata:true" "http://169.254.169.254/metadata/instance/compute/name?api-version=2017-08-01&format=text")
    if [ $? != 0 ] ; then
        echo -e "\n\nWARNING\n\nFailed to retrieve instance name\n\n"
    elif [ "$pass" = "" ] ; then
        echo -e "\n\nWARNING\n\nInvalid instance name value\n\n"
    else
        /usr/share/untangle/bin/ut-set-admin-passwd.py "$pass"
    fi

    # remove this script
    /bin/rm -f $0
fi
