#! /bin/bash

### This can only run if untangle-qemu-run-uvm has been started
### already (because it needs the presence of the client bridge)

set -e

usage() {
  echo "$0 -f <image-file> -k <kernel> -i <initrd> [-m <memory>] [-t (g|graphic|t|terminal)]"
  exit 1
}

if [ $(id -u) != 0 ] ; then
  exec sudo -E $0 $*
fi

#############
#############
## CLI args
#############
#############
while getopts f:m:t: option ; do
  case "$option" in
    f) IMAGE="$OPTARG" ;;
    m) MEMORY="$OPTARG" ;;
    t) case $OPTARG in
	 g|graphic) MODE="-monitor stdio" ;;
	 t|terminal) MODE="-nographic" ;;
	 *) usage ;;
       esac ;;
    h) usage ;;
    \?) usage ;;
  esac
done

#########
#########
## main
#########
#########

##################
# check CLI args
[[ -z "$IMAGE" ]] && usage

# default RAM to 1G
[[ -z "$MEMORY" ]] && MEMORY="1G"

# default MODE to graphical
[[ -z "$MODE" ]] && MODE="-monitor stdio"

BRIDGE_INT="qemubr-int0"

################
# start the VM
kvm -enable-kvm \
    -m $MEMORY \
    -drive if=none,format=raw,id=hd0,file=$IMAGE \
    -device driver=virtio-blk-pci,id=drive0,drive=hd0 \
    $MODE \
    -netdev bridge,id=internal0,br=$BRIDGE_INT \
    -device virtio-net-pci,netdev=internal0
