#! /bin/bash

### This can only run if untangle-qemu-run-uvm has been started
### already (because it needs the presence of the client bridge)

set -e

usage() {
  echo "$0 -f <image-file> -k <kernel> -i <initrd> [-m <memory>]"
  exit 1
}

if [ $(id -u) != 0 ] ; then
  exec sudo -E $0 $*
fi

#############
#############
## CLI args
#############
#############
while getopts f:m: option ; do
  case "$option" in
    f) IMAGE="$OPTARG" ;;
    m) MEMORY="$OPTARG" ;;
    h) usage ;;
    \?) usage ;;
  esac
done

#########
#########
## main
#########
#########

##################
# check CLI args
[[ -z "$IMAGE" ]] && usage

# default RAM to 1G
[[ -z "$MEMORY" ]] && MEMORY="1G"

QEMU_SOCKET_PORT="12345"

################
# start the VM
kvm -enable-kvm \
    -m $MEMORY \
    -drive if=none,format=raw,id=hd0,file=$IMAGE \
    -device driver=virtio-blk-pci,id=drive0,drive=hd0 \
    -monitor stdio \
    -netdev socket,id=internal0,connect=:$QEMU_SOCKET_PORT \
    -device virtio-net-pci,netdev=internal0
