#! /bin/bash

set -e

usage() {
  echo "$0 -f <output-file> [-r <repository>] [-a <arch>]"
  exit 1
}

if [ $(id -u) != 0 ] ; then
  exec sudo -E $0 $*
fi

### CLI args
while getopts f:r:a: option ; do
  case "$option" in
    r) REPOSITORY="$OPTARG" ;;
    f) IMAGE="$OPTARG" ;;
    a) ARCH="$OPTARG" ;;
    h) usage ;;
    \?) usage ;;
  esac
done

## main
[[ -z "$IMAGE" ]] && usage
if [[ -e $IMAGE ]] ; then
  echo "$IMAGE already exists, please remove it manually"
  exit 1
fi

[[ -z "$ARCH" ]] && ARCH="amd64"
[[ -z "$REPOSITORY" ]] && REPOSITORY="stretch"

CUSTOM_DIR=$(readlink -f $(dirname $0))/vmdebootstrap

vmdebootstrap --arch $ARCH \
              --distribution $REPOSITORY \
	      --mirror http://package-server.untangle.int/public/$REPOSITORY \
	      --image $IMAGE \
	      --size 10G \
	      --no-mbr \
	      --verbose \
	      --root-password passwd \
	      --hostname uvm-${REPOSITORY}-${ARCH} \
	      --no-systemd-networkd \
	      --no-kernel \
	      --sparse \
	      --debootstrapopts="no-check-gpg components=main,non-free" \
	      --customize=${CUSTOM_DIR}/kill-gpg-agent.sh \
	      --package untangle-gateway \
	      --package postgresql-client-9.6 \
	      --package postgresql-9.6 \
	      --package openjdk-8-jre \
	      --package perl-openssl-defaults \
	      --package lhasa \
	      --package zoo \
	      --package libfreeradius-dev
