#! /bin/bash

set -e

usage() {
  echo "$0 -f <image-file> -k <kernel> -i <initrd> -n <nic-to-bridge> [-m <memory>] [-t (g|graphic|t|terminal)]"
  exit 1
}

if [ $(id -u) != 0 ] ; then
  exec sudo -E $0 $*
fi

#############
#############
## CLI args
#############
#############
while getopts f:k:i:m:n:t: option ; do
  case "$option" in
    k) KERNEL="$OPTARG" ;;
    f) IMAGE="$OPTARG" ;;
    i) INITRD="$OPTARG" ;;
    m) MEMORY="$OPTARG" ;;
    n) NIC="$OPTARG" ;;
    t) case $OPTARG in
	 g|graphic) MODE="-monitor stdio" ;;
	 t|terminal) MODE="-nographic" ;;
	 *) usage ;;
       esac ;;
    h) usage ;;
    \?) usage ;;
  esac
done

#########
#########
## main
#########
#########

##################
# check CLI args
{ [[ -z "$IMAGE" ]] || [[ -z "$KERNEL" ]] || [[ -z "$INITRD" ]] || [[ -z $NIC ]] ; } && usage

# default RAM to 2G
[[ -z "$MEMORY" ]] && MEMORY="2G"

# default MODE to graphical
[[ -z "$MODE" ]] && MODE="-monitor stdio"

#####################################################################
# setup bridge networking for both external and internal interfaces
# in the VM

# FIXME: support multiples bridges and qemu instances, by supporting
#        bridge-(ext|int)N instead of just bridge-(ext|int)0

# setup bridge for external interface
# FIXME: adding $NIC with an already-defined IP, to a bridge without
#        an IP, messes up ARP and access to the $NIC's subnet from the
#        host itself. Any traffic that's routed to the outside is
#        fine, though.  To fix that, I manually force my subnet traffic
#        on the bridge interface:
#   ip route del default dev $NIC
#   ip route del 172.16.25.0/24 dev $NIC
#   ip route add 172.16.25.0/24 dev $BRIDGE_EXT
#   ip route add default via 172.16.25.1

BRIDGE_EXT="qemubr-ext0"
if ! ip link ls ${BRIDGE_EXT} > /dev/null 2>&1 ; then
    ip link add $BRIDGE_EXT type bridge
    ip link set dev $BRIDGE_EXT up
fi
ip link set $NIC master $BRIDGE_EXT || true

# setup bridge for internal interface
BRIDGE_INT="qemubr-int0"
if ! ip link ls ${BRIDGE_INT} > /dev/null 2>&1 ; then
    ip link add $BRIDGE_INT type bridge
    ip link set dev $BRIDGE_INT up
    ip route add 192.168.2.0/24 dev $BRIDGE_INT
fi

# make sure we remove $NIC from the ext bridge upon exiting
trap "ip link set $NIC nomaster" 0

########################
# load required modules
modprobe virtio-blk
modprobe virtio-pci

QEMU_SOCKET_PORT="12345"

########################
# start the Untangle VM
kvm -enable-kvm \
    -m $MEMORY \
    -kernel $KERNEL \
    -initrd $INITRD \
    -drive if=none,format=raw,id=hd0,file=$IMAGE \
    -device driver=virtio-blk-pci,id=drive0,drive=hd0 \
    $MODE \
    -append "root=/dev/vda1 net.ifnames=0 console=tty0 console=ttyS0,115200" \
    -netdev bridge,id=external0,br=$BRIDGE_EXT \
    -device virtio-net-pci,netdev=external0 \
    -netdev socket,id=internal0,listen=:$QEMU_SOCKET_PORT \
    -device virtio-net-pci,netdev=internal0
