#! /bin/bash

# attempt to fix bug #7974

if ! grep -q 'HWCLOCKPARM' /etc/default/rcS > /dev/null 2>&1 ; then
  echo "HWCLOCKPARS=--directisa" >> /etc/default/rcS
fi

# tell cron not to send emails
if [ -e /etc/crontab ] ; then
  if ! grep -q MAILTO /etc/crontab ; then
    sed -e '/SHELL/i MAILTO=""' -i /etc/crontab
  else
    sed -e 's/.*MAILTO=.*/MAILTO=""/' -i /etc/crontab
  fi
fi

perl -i -pe 's/FSCKFIX=.*/FSCKFIX=yes/' /etc/default/rcS

exit 0
