#! /bin/sh

# do not start sshd by default if this is the first install
if [ "$1" = "install" ] ; then
  mkdir -p /etc/ssh
  touch /etc/ssh/sshd_not_to_be_run
fi

perl -i -pe 's/FSCKFIX=.*/FSCKFIX=yes/' /etc/default/rcS

exit 0
