#!/bin/sh

if [ $# -gt 0 ] ; then
    # this is for started from init.d
    FLAG=1 # reboot after quit
else 
    # this is for started from X
    FLAG=0 # start mvvm after quit
fi

reboot() {
    echo Reboot
    /sbin/shutdown -r now
}

quit() {
    echo Quit
    if [ -x /etc/init.d/mvvm ] ; then
        /etc/init.d/mvvm start
    fi
    exit
}

if [ $FLAG -eq 1 ] ; then
    trap reboot 6
    trap reboot 15
    trap reboot 2
else
    trap quit 6
    trap quit 15
    trap quit 2
fi


INST_OPTS=" -o DPkg::Options::=--force-confnew --yes --force-yes --fix-broken "
UPGD_OPTS=" -o DPkg::Options::=--force-confnew --yes --force-yes --fix-broken "
tmpfile=$(tempfile)
backtitle="Metavize EdgeGuard"

confirm_exit()
{
    dialog --backtitle "$backtitle" --title "Confirm" \
        --yesno "Are you sure you wish to exit?" 6 52

    case $? in
        0) # yes
            state=END_STATE
            ;;
        1) # no
            state=MAIN_MENU
            ;;
    esac
}

success_splash()
{
    dialog --backtitle "$backtitle" --title "Complete" \
        --msgbox "Settings Applied" 10 61 

    state=MAIN_MENU
}

restore_menu()
{
    dialog --backtitle "$backtitle" --title "EdgeGuard Backup & Restore" \
        --menu "Choose operation:" 10 61 2 \
        "Backup / Restore" "" \
        "Return to Factory Defaults" "" \
        2>$tmpfile
    retval=$?

    choice=$(cat $tmpfile)
    case $retval in
        0) # OK
            case $choice in
                "Backup / Restore")
                    if [ -x ./mvvmdb-restore ] ; then
                        ./mvvmdb-restore
                    fi
                    state=MAIN_MENU
                    ;;
                "Return to Factory Defaults")
                    if [ -x /usr/bin/purgedb ] ; then
                        /usr/bin/purgedb
                    fi
                    state=SUCCESS_SPLASH
                    ;;
                *)
                    echo "Invalid Option: $choice"
                    cat $tmpfile
                    exit
            esac
            ;;
        1) # Cancel
            state=MAIN_MENU
            ;;
    esac
}

support_menu()
{
    dialog --backtitle "$backtitle" --title "EdgeGuard Support" \
        --menu "Choose operation:" 10 61 2 \
        "Enable Remote Support" "" \
        "Disable Remote Support" "" \
        2>$tmpfile
    retval=$?

    choice=$(cat $tmpfile)
    case $retval in
        0) # OK
            case $choice in
                "Enable Remote Support")
                    /etc/init.d/ssh start &> /dev/null
                    update-rc.d ssh defaults &> /dev/null
                    state=SUCCESS_SPLASH
                    ;;
                "Disable Remote Support")
                    /etc/init.d/ssh stop &> /dev/null
                    mv /etc/init.d/ssh /etc/init.d/ssh.tmp &> /dev/null
                    update-rc.d ssh remove &> /dev/null
                    mv /etc/init.d/ssh.tmp /etc/init.d/ssh &> /dev/null
                    state=SUCCESS_SPLASH
                    ;;
                *)
                    echo "Invalid Option: $choice"
                    cat $tmpfile
                    exit
            esac
            ;;
        1) # Cancel
            state=MAIN_MENU
            ;;
    esac
}

upgrade_menu()
{
    dialog --backtitle "$backtitle" --title "EdgeGuard Upgrade" \
        --menu "Choose operation:" 10 61 3 \
        "Upgrade EdgeGuard" "" \
        "Resume Halted Upgrade" "" \
        "Fix Halted Upgrade" "" \
        2>$tmpfile
    retval=$?

    choice=$(cat $tmpfile)
    case $retval in
        0) # OK
            case $choice in
                "Upgrade EdgeGuard")
                    apt-get upgrade $UPGD_OPTS
                    state=SUCCESS_SPLASH
                    ;;
                "Resume Halted Upgrade")
                    dpkg --configure -a
                    state=SUCCESS_SPLASH
                    ;;
                "Fix Halted Upgrade")
                    apt-get -f install $INST_OPTS
                    state=SUCCESS_SPLASH
                    ;;
                *)
                    echo "Invalid Option: $choice"
                    cat $tmpfile
                    exit
            esac
            ;;
        1) # Cancel
            state=MAIN_MENU
            ;;
    esac
}

main_menu()
{
    dialog --backtitle "$backtitle" --title "EdgeGuard Recovery" \
        --cancel-label "Exit" \
        --menu "Choose operation:" 10 61 3 \
        "Backup & Restore" "" \
        "Upgrade EdgeGuard" "" \
        "Remote Support" "" \
        2>$tmpfile
    retval=$?

    choice=$(cat $tmpfile)
    case $retval in
        0) # OK
            case $choice in
                "Backup & Restore")
                    state=RESTORE_MENU
                    ;;
                "Upgrade EdgeGuard")
                    state=UPGRADE_MENU
                    ;;
                "Remote Support")
                    state=SUPPORT_MENU
                    ;;
            esac
            ;;
        1) # Cancel
            state=CONFIRM_EXIT
            ;;
    esac
}
















# Stop the mvvm
if [ -x /etc/init.d/mvvm ] ; then
    /etc/init.d/mvvm stop
fi

state=MAIN_MENU
while true; do
    case $state in
# Main levels
        MAIN_MENU)
            main_menu
            ;;
# Sub levels
        RESTORE_MENU)
            restore_menu
            ;;
        UPGRADE_MENU)
            upgrade_menu
            ;;
        SUPPORT_MENU)
            support_menu
            ;;
# Messages
        SUCCESS_SPLASH)
            success_splash
            ;;
# Exit levels
        CONFIRM_EXIT)
            confirm_exit
            ;;
        END_STATE)
            if [ $FLAG -eq 1 ] ; then
                reboot
            else
                quit
            fi
            ;;
        *)
            echo "no such state: $state"
            exit
    esac
done

