#!/bin/sh

INST_OPTS=" -o DPkg::Options::=--force-confnew --yes --force-yes --fix-broken "
UPGD_OPTS=" -o DPkg::Options::=--force-confnew --yes --force-yes --fix-broken "

restore_db()
{
    infile=$1

    dropdb -U postgres mvvm >/dev/null 2>&1
    createdb -U metavize mvvm >/dev/null 2>&1

    if confirm "Restore settings?"; then
        zcat $infile | psql -U postgres mvvm >/dev/null 2>&1

        ## Set the unconfigured flag, so the box will reconfigure the network configuration a restart
        echo "update mvvm_network_settings set setup_state=67 where setup_state=3" \
            | psql -U postgres mvvm >/dev/null 2>&1
        echo "update mvvm_network_settings set setup_state=68 where setup_state=4" \
            | psql -U postgres mvvm >/dev/null 2>&1
    fi
}

restore_packages()
{
    instfile=$1

    cat $instfile | cut -d' ' -f1 | grep -- '-storeitem$' \
        | xargs apt-get install $INST_OPTS
    apt-get dist-upgrade $UPGD_OPTS
    /etc/init.d/mvvm stop
}


if [ $# -lt 3 ] ; then 
    echo "Usage: $0 dumpfile tarfile instfile"
fi

dumpfile=$1
tarfile=$2
instfile=$3

# stop the MVVM, depending on circumstances may already be stopped
/etc/init.d/mvvm stop

# restore the database and the /usr/share/metavize important stuff
restore_db $dumpfile && tar zxf $tarfile -C /

# try to download needed files, this may fail because the network settings may not be correct
restore_packages $instfile

# restart the networking with new settings
/etc/init.d/networking restart

# try again just in case these network settings are "better" than the previous
restore_packages $instfile

# start the MVVM, depending on circumstances (menu driven restore) may need to be restopped 
/etc/init.d/mvvm start 2>&1 > /dev/null

