#! /bin/dash

mkdir -p /var/log/untangle-net-alpaca/
exec >> /var/log/untangle-net-alpaca/cron.log 2>&1

NAME="untangle-net-alpaca"
BASE_DIR="/var/lib/rails/untangle-net-alpaca"

if [ -r /etc/default/$NAME ]; then
    . /etc/default/$NAME
fi

ruby ${BASE_DIR}/usr/share/untangle-net-alpaca/scripts/cleanup.rb ${BASE_DIR}
exit 0
