#! /bin/dash

mkdir -p /var/log/untangle-net-alpaca/
exec >> /var/log/untangle-net-alpaca/cron.log 2>&1

NAME="untangle-net-alpaca"
BASE_DIR="/var/lib/rails/untangle-net-alpaca"

if [ -r /etc/default/$NAME ]; then
    . /etc/default/$NAME
fi

ruby /usr/share/untangle-net-alpaca/scripts/cleanup.rb ${BASE_DIR}


## Clean out the temporary files
USER_COMMAND_DIRECTORY="/tmp/alpaca"
if [ -d "${USER_COMMAND_DIRECTORY}" ]; then
    find "${USER_COMMAND_DIRECTORY}" -maxdepth 1 -type f -name "command-*" -atime +1 -print0 | xargs -0 rm -f  
fi
exit 0
