#!/bin/dash

## Creates a file with two nonces.  The first nonce is always used to
## authenticate.  When authenticating, the server should check if
## either nonce is matches.  This way, if the client authenticates
## precisely when the nonce changes, then there request will still be
## valid.

NONCE_FILE=/etc/untangle-net-alpaca/nonce

NEW_NONCE_FILE=`mktemp`

nonce()
{
    openssl rand -out /dev/stdout -base64 512 2>/dev/null | md5sum | awk '{ print $1 }'
}

## Create a new nonce
nonce >| ${NEW_NONCE_FILE}

## Append the old nonce
head -n 1 ${NONCE_FILE} >> ${NEW_NONCE_FILE}

## Move the new nonces into the correct location
mv ${NEW_NONCE_FILE} ${NONCE_FILE}

## Only root should be able to view this file
chown root:root ${NONCE_FILE}
chmod 600 ${NONCE_FILE}
