#!/bin/sh
module="n22xxed"
device="n22xxed"
prog=$(basename $0)
logger="logger -t $prog"
kernel=`uname -r`

if uname -r | grep amd64 -q
then
   arch="amd64"
   $logger "amd64 detected"
else
   arch="i386"
   $logger "i386 detected"
fi
util="/usr/bin/n22xxed_util_$arch"
mode="664"

# If the old driver exists, remove it before starting up new driver
if -f /lib/modules/$kernel/drivers/net/igb/igb.ko; then
  rmmod igb
  rm -f /lib/modules/$kernel/drivers/net/igb/igb.ko
  depmod -a
  modprobe igb
fi

#Check and see if igb is already loaded, if not, load it!
lsmod | grep igb -q
if [ $? -ne 0 ]; then
  $logger "loading intel NIC driver kernel module"
  modprobe igb
fi

$logger "loading niagara kernel module"
modprobe $module

# Group: since distributions do it differently, look for wheel or use staff
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi

# remove stale nodes
$logger "Creating /dev/$device entry"
rm -f /dev/${device}? 

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

mknod /dev/${device}0 c $major 0
ln -sf ${device}0  /dev/${device}

# give appropriate group/permissions
chgrp $group /dev/${device}0
chmod $mode  /dev/${device}0

# run the utility to force active mode until we go down.
$logger "Switching Card to active mode"
$util -a | $logger