#! /bin/bash

# Comment out annoying warning from mountnfs script 
# That gets printed during /etc/init.d/networking restart
sed -e 's/\(.*log_warning_msg.*\)/#\1/' -i /etc/network/if-up.d/mountnfs

# FIXME 
# this is just for devel
# This is so I don't have to write converters, it just nukes a rewrites all scripts
# This should be removed
# FIXME
# if [ -f /etc/untangle-netd/network.js ] ; then
#     echo "Updating hooks..."
#     rm -f /etc/untangle-netd/iptables-rules.d/*
#     rm -f /etc/untangle-netd/post-network-hook.d/*
#     rm -f /etc/untangle-netd/pre-network-hook.d/*
#     /usr/share/untangle-netd/bin/sync-settings.py -vv -f /etc/untangle-netd/network.js
# elif [ -f /usr/share/untangle/settings/untangle-vm/network.js ] ; then
#     echo "Updating hooks..."
#     rm -f /etc/untangle-netd/iptables-rules.d/*
#     rm -f /etc/untangle-netd/post-network-hook.d/*
#     rm -f /etc/untangle-netd/pre-network-hook.d/*
#     /usr/share/untangle-netd/bin/sync-settings.py -vv -f /usr/share/untangle/settings/untangle-vm/network.js
# fi