#! /bin/bash

# Comment out annoying warning from mountnfs script 
# That gets printed during /etc/init.d/networking restart
sed -e 's/\(.*log_warning_msg.*\)/#\1/' -i /etc/network/if-up.d/mountnfs

# disable keepalived in sysvinit
# It will be started via the post-network scripts if needed
update-rc.d keepalived disable

# 11.1 conversion
rm -f /etc/untangle-netd/iptables-rules.d/340-dns-rules

# 12.0 conversion
rm -f /etc/untangle-netd/post-network-hook.d/100-finddev

exit 0
