#!/bin/sh

if [ "x$1" == "xpurge" ] ; then
    # leave used flag 
    mkdir -p /usr/share/untangle/conf/trials &> /dev/null
    touch /usr/share/untangle/conf/trials/clamphish.expired

    # remove my at jobs
    for i in `atq | awk '{print $1}'` ; do 
        if [ ! -z "`at -c $i | grep \"clamphish-transform\"`" ] ; then
            atrm $i
        fi
    done

    # reenable usage
    mcli enable clamphish-transform &> /dev/null
    # change extraname to nothing
    mcli extraname clamphish-transform "" &> /dev/null &
fi

exit 0


