#!/bin/dash

BACKUP_FILE=$0

if [ -z "${BACKUP_FILE}" ] || [ "${BACKUP_FILE%.uab}x" = "${BACKUP_FILE}x" ]; then
    echo "USAGE: $0 <file-name> [<description>]"
    echo "\t<file-name>: Backup file to create."
    echo "\t<description>: Description of the backup file."
    exit 0
fi

BASE_DIR=untangle-net-alpaca/files/var/lib/rails/untangle-net-alpaca

if [ -f /etc/default/untangle-net-alpaca ]; then
    . /etc/default/untangle-net-alpaca
fi

## Create a temporary directory to place everything
BACKUP_DIRECTORY=`mktemp -d`

<<EOF > ${BACKUP_DIRECTORY}

EOF

