#!/bin/dash

get_pppoe_name()
{
   local t_name
   local t_intf_name
   local t_pid_file
   local t_pid
   
   t_intf_name=$1
   
   for t_pid_file in /var/run/ppp*.pid ; do 
     t_pid=`head -n 1 $t_pid_file`
     grep -q "connection.${t_intf_name}" /proc/${t_pid}/cmdline 2>/dev/null  > /dev/null
     if [ "$?" != 0 ]; then
       continue
     fi
     echo "`basename ${t_pid_file}`" | sed 's|.pid||'
     return
   done 

   ## This doesn't actually work, but it acts as a placeholder.
   echo "ppp.${t_intf_name}"
}


if [ -z "$1"  ]; then
    echo "FAIL, specify an ethernet name, defaulting to ppp0" >&2
    echo "ppp0"
    exit 0
fi

get_pppoe_name $1
