#! /bin/sh

set -x
set -e

# load modules
modprobe dhd
modprobe wl

# make sure they show up in ifconfig
ifconfig eth1 up
ifconfig eth2 up

# disable hostapd (we use broadcom drivers inside ddwrt to drive wireless)
if [ -f /etc/init.d/hostapd ] ; then
    mv /etc/init.d/hostapd /etc/init.d/hostapd.disabled
fi

exit 0
