#! /bin/sh

set -e

version=$(uname -r)

# unload existing module if it is loaded
if lsmod | grep -q igb ; then
  rmmod igb
fi

# delete the old igb kernel module
rm -f /lib/modules/$version/kernel/drivers/net/igb/igb.ko

mkdir -p /lib/modules/$version/extra/
cp -f /usr/share/untangle-tangent-kernel/$version/*.ko /lib/modules/$version/extra/
depmod -a

exit 0
