#!/bin/sh

BASE_DIR=/usr/share/untangle-nsis-addons
LIST=${BASE_DIR}/copied-files
DEST_DIR=/usr/share/nsis

for i in `find ${BASE_DIR} -type f` ; do 
    if [ "$i" = "${LIST}" ]; then 
        continue ;
    fi

    relativePath=${i#${BASE_DIR}/}
    if [ ! -f ${DEST_DIR}/${relativePath} ] ; then
        echo ${relativePath} >> $LIST
        mkdir -p `dirname ${DEST_DIR}/${relativePath}`
        cp -r $i ${DEST_DIR}/${relativePath}
    fi
done

