#! /bin/bash

DEFAULT_FILE="/etc/default/snmpd"

deb-systemd-helper disable snmpd.service

# Only for first time installation.
if [ -z "$2" ] && ! grep -q "UDP" $DEFAULT_FILE ; then
   # Disable by default (enabled by setting snmp settings in UI)
   deb-systemd-invoke stop snmpd
   sed -i "s/^SNMPDRUN=.*/SNMPDRUN=no/" $DEFAULT_FILE
   sed -i "s/^TRAPDRUN=.*/TRAPDRUN=no/" $DEFAULT_FILE
fi

    
exit 0
