#!/bin/sh

cp -f /usr/share/untangle-lxc-client/default.conf /etc/lxc

# delete old files
rm -f /etc/network/interfaces.d/lxcbr0
rm -rf /etc/untangle/lxc-client.d
rm -f /etc/init.d/untangle-lxc-client

# disable the service from auto-starting
# NGFW-11687
deb-systemd-helper disable untangle-lxc-client.service

#DEBHELPER#

exit 0
