class OSLibrary::Debian::NetworkManager < OSLibrary::NetworkManager
  include Singleton

  Service = "/etc/init.d/networking"
  InterfacesConfigFile = "/etc/network/interfaces"

  def interfaces
    logger.debug( "Running inside of the network manager for debian" )

    interfaceArray = []

    devices=`find /sys/devices -name 'net:*' | sed 's|.*net:||'`

    ## This is test code to fake a third interface
    devices << "dummy0" if File.exists?( "/sys/class/net/dummy0" )

    devices.each do |os_name|
      os_name = os_name.strip

      bus_id=""
      mac_address = File.open( "/sys/class/net/#{os_name}/address", "r" ) { |f| f.readline.strip }

      interfaceArray << PhysicalInterface.new( os_name, mac_address, bus_id )
    end
    
    interfaceArray
  end

  def commit
    interfaces_file = []
    interfaces_file << header
    Interface.find( :all ).each do |interface| 
      case interface.config_type
      when InterfaceHelper::ConfigType::STATIC
        interfaces_file << static( interface )
      when InterfaceHelper::ConfigType::DYNAMIC
        interfaces_file << dynamic( interface )
      when InterfaceHelper::ConfigType::BRIDGE
        interfaces_file << bridge( interface )
      end
    end

    ## Just write out the file for now.
    File.open( InterfacesConfigFile, "w" ) { |f| f.print( interfaces_file.join( "\n" )) }
    
    ## Restart networking
    raise "Unable to reconfigure network settings" unless Kernel.system( "#{Service} restart" )
  end

  ## Dump out the configuration for a statically configured interface.
  def static( interface )
    ## Index of the interface that is being configured (nil for th first one)
    i = nil

    ## name of the interface
    name = interface.os_name
    
    static = interface.intf_static
    
    if static.nil?
      logger.warn( "The interface #{interface} is not configured" )
      return ""
    end

    ## Configure each IP and then join it all together with some newlines.
    interface.intf_static.ip_networks.map do |ip_network|
      ip_network_name = "#{name}#{i.nil? ? "" : ":#{i}"}"
      i = i.nil? ? 0 : i + 1

      <<EOF
auto #{ip_network_name}
iface #{ip_network_name} inet static
\taddress #{ip_network.ip}
\tnetmask #{OSLibrary::NetworkManager.parseNetmask( ip_network.netmask)}
EOF
    end.join( "\n" )
  end

  def dynamic( interface )
    ""
  end

  def bridge( interface )
    ""
  end

  def header
    <<EOF
## Auto Generated by the Untangle Net Urchin
## If you modify this file manually, your changes
## may be overriden

## Configuration for the loopback interface
auto lo
iface lo inet loopback
EOF
  end
end
