#!/bin/sh

SERVICE=${DPKG_MAINTSCRIPT_PACKAGE}

ourInit() {
if [ -x /usr/sbin/invoke-rc.d ] && [ ! "`readlink /usr/sbin/invoke-rc.d`" = /bin/true ] ; then
  invoke-rc.d $1 $2
else
  /etc/init.d/$1 $2
fi
}

if [ -x "/etc/init.d/${SERVICE}" ]; then
  update-rc.d ${SERVICE} defaults 10 >/dev/null # early on
  ourInit ${SERVICE} restart
fi

swapNic() {
    udev_file='/etc/udev/rules.d/70-persistent-net.rules';
    echo "Moving interface ${1} to ${2}"
    perl -i -pe "s/NAME\=\"${1}\"/NAME\=\"new_${2}\"/g" $udev_file
}

swapNicFinish() {
    # then remove all the "new_".  We do the intermeidate step to avoid renaming collisions
    udev_file='/etc/udev/rules.d/70-persistent-net.rules';
    perl -i -pe "s/new_//g" $udev_file 
}

# Swap eth1 and eth2 so order is correct on faceplate
# Do this only on new install of this package
if [ -z "$2" ] ; then
    swapNic eth1 eth2
    swapNic eth2 eth1
    swapNicFinish
fi

exit 0
