#!/bin/bash

UDEV_FILE="/etc/udev/rules.d/70-persistent-net.rules"

systemctl restart untangle-hardware-config

getMacForInterface() {
  ip link show $1 | awk '/ether/ {print $2}'
}

generateUdevRule() {
  echo 'SUBSYSTEM=="net", ACTION=="add", DRIVERS=="?*", ATTR{address}=="'$1'", ATTR{dev_id}=="0x0", ATTR{type}=="1", KERNEL=="eth*", NAME="'$2'"'
}

moveNic() {
  mac=$(getMacForInterface $1)
  echo "Moving interface $1 ($mac) to $2"
  generateUdevRule $mac $2 >> $UDEV_FILE
}

# Assign the following (only on new install of this package):
# eth1 -> eth3
# eth2 -> eth1
# eth3 -> eth2
if [ -z "$2" ] ; then
    moveNic eth1 eth3
    moveNic eth2 eth1
    moveNic eth3 eth2
fi

exit 0
