#! /bin/bash

MAILDIR=/var/mail

chown root:mail $MAILDIR
chmod 2775 $MAILDIR

# allow MX records to point at internal IPs
perl -0777 -i -pe 's|ignore_target_hosts.*?no_more|ignore_target_hosts = 0.0.0.0 : 255.255.255.255 : 169.254.0.0/16\n  no_more|s' /etc/exim4/exim4.conf.template /etc/exim4/conf.d/router/200_exim4-config_primary

# redirect root mail to blackhole
if [ -z "`grep '^root:' /etc/aliases`" ] ; then
    echo "root: :blackhole:" >> /etc/aliases
else
    sed -e "s/^root:.*/root: :blackhole:/" -i /etc/aliases
fi

exit 0
