#! /bin/dash

# These variables are for the use of the scripts run by run-parts
# PPP_IFACE="$1"
# PPP_TTY="$2"
# PPP_SPEED="$3"
# PPP_LOCAL="$4"
# PPP_REMOTE="$5"
# PPP_IPPARAM="$6"

# redirect to logfile and stdout
mkdir -p /var/log/uvm/
LOGFILE="/var/log/uvm/pppoe.log"
mkfifo ${LOGFILE}.pipe
tee < ${LOGFILE}.pipe $LOGFILE &
exec >> ${LOGFILE}.pipe 2>&1
rm ${LOGFILE}.pipe

write_status_file()
{
    local t_interface="$1"
    local t_index="$2"
    ( [ -z "$t_interface" ] || [ -z "$t_index" ] ) && {
        return 0
    }

    /bin/echo -e "[DEBUG: `date`] Writing /var/lib/untangle-netd/interface-${t_index}-status.js"
    /usr/share/untangle-netd/bin/write-interface-status.py -I ${t_interface} -i ${t_index} -w /var/lib/untangle-netd/interface-${t_index}-status.js

    /bin/echo -e "[DEBUG: `date`] Writing /var/lib/untangle-netd/interface-${t_interface}-status.js"
    /usr/share/untangle-netd/bin/write-interface-status.py -I ${t_interface} -i ${t_index} -w /var/lib/untangle-netd/interface-${t_interface}-status.js
}

make_resolv_conf() { 
    ## This guarantees that ${t_new_domain_name_servers} will just be " "
    local t_new_domain_name_servers="`echo "${DNS1}\n${DNS2}" | sort | uniq`"
    
    ## Check MS_DNSx if the DNS servers were not specified in DNS1 and DNS2
    test -z "${t_new_domain_name_servers}" && {
        t_new_domain_name_servers=`echo "${MS_DNS1}\n${MS_DNS2}" | sort | uniq`
    }

    ## only update the dns server when instructed to.
    if [ -n "${t_new_domain_name_servers}" ] && [ "${USEPEERDNS}x" = "1x" ]; then
        local t_hash="`md5sum /etc/dnsmasq.conf`"
        
        if [ -n "$t_new_domain_name_servers" ]; then
            for nameserver in $t_new_domain_name_servers ; do
                /bin/echo -e "#new_name_server=${nameserver} # uplink.${PPPOE_UPLINK_INDEX}" >> /etc/dnsmasq.conf
            done
            
            sed -i -e "/^#*\s*server=.*uplink.${PPPOE_UPLINK_INDEX}/d" -e 's/^#new_name_server=/server=/' /etc/dnsmasq.conf
        fi

        local t_new_hash="`md5sum /etc/dnsmasq.conf`"
                    
        ## Reststart dnsmasq if necessary
        if [ "${t_hash}x" != "${t_new_hash}x" ]; then
            /bin/echo -e "[DEBUG: `date`] Restarting dnsmasq..."
            /etc/init.d/dnsmasq restart
        else
            /bin/echo -e "[DEBUG: `date`] Skipping dnsmasq restart"
        fi
    fi

    return 0
}

PPP_PID=`cat /var/run/${PPP_IFACE}.pid`
CONNECTION_FILE=`cat "/proc/${PPP_PID}/cmdline" | tr '\000' '\001' | awk -v RS='\001' '/^connection./ { print ; exit }'`
PPPOE_UPLINK_INDEX=`echo ${CONNECTION_FILE} | sed -e 's/connection\.intf//'`

/bin/echo -e "[DEBUG: `date`] Interface index: ${PPPOE_UPLINK_INDEX}"

if [ -z "${PPPOE_UPLINK_INDEX}" ]; then
    /bin/echo -e "[DEBUG: `date`] Unknown interface index! Quitting..."
    return
fi

make_resolv_conf

/usr/share/untangle-netd/bin/add-uplink.sh ${PPP_IFACE} dev "uplink.${PPPOE_UPLINK_INDEX}"

write_status_file ${PPP_IFACE} ${PPPOE_UPLINK_INDEX}

# FIXME - should we run this here?
# run-parts /etc/untangle-netd/post-network-hook.d

true
