#! /bin/bash

# This script handles the netd_bridge_mtu options by settings the MTU on all ports

# FIXME what is this? is it necessary?
## Done here so the setting takes effect every time, not just when the bridge is created.
if [ "$IF_NETD_BRIDGE_MTU" ]; then
    for port in $IF_BRIDGE_PORTS ; do
        ifconfig ${port} mtu $IF_NETD_BRIDGE_MTU
    done

    ## don't believe this is necessary, but it can't hurt
    ifconfig ${IFACE} mtu $IF_NETD_BRIDGE_MTU
fi

exit 0