#!/bin/sh

ourInit() {
if [ -x /usr/sbin/invoke-rc.d ] && [ ! "`readlink /usr/sbin/invoke-rc.d`" = /bin/true ] ; then
  invoke-rc.d $1 $2
else
  /etc/init.d/$1 $2
fi
}

mkdir -p /var/log/untangle-shield || true

# untangle-shield is started by the node.
#if [ -x "/etc/init.d/untangle-shield" ]; then
#    update-rc.d untangle-shield defaults >/dev/null
#    ourInit untangle-shield start || true
#fi

exit 0
