exp_exec_prefix = /usr
rel_exec_prefix = /usr
exp_bindir = /usr/bin
rel_bindir = /usr/bin
exp_sbindir = /usr/sbin
rel_sbindir = /usr/sbin
exp_libdir = /usr/lib
rel_libdir = /usr/lib
exp_libexecdir = /usr/lib/apache2/modules
rel_libexecdir = /usr/lib/apache2/modules
exp_mandir = /usr/share/man
rel_mandir = /usr/share/man
exp_sysconfdir = /etc/apache2
rel_sysconfdir = /etc/apache2
exp_datadir = /usr/share/apache2
rel_datadir = /usr/share/apache2
exp_installbuilddir = /usr/share/apache2/build
rel_installbuilddir = /usr/share/apache2/build
exp_errordir = /usr/share/apache2/error
rel_errordir = /usr/share/apache2/error
exp_iconsdir = /usr/share/apache2/icons
rel_iconsdir = /usr/share/apache2/icons
exp_htdocsdir = /usr/share/apache2/default-site/htdocs
rel_htdocsdir = /usr/share/apache2/default-site/htdocs
exp_manualdir = /usr/share/apache2/default-site/htdocs/manual
rel_manualdir = /usr/share/apache2/default-site/htdocs/manual
exp_cgidir = /usr/lib/cgi-bin
rel_cgidir = /usr/lib/cgi-bin
exp_includedir = /usr/include/apache2
rel_includedir = /usr/include/apache2
exp_localstatedir = /var/run
rel_localstatedir = /var/run
exp_runtimedir = /var/run
rel_runtimedir = /var/run
exp_logfiledir = /var/log/apache2
rel_logfiledir = /var/log/apache2
exp_proxycachedir = /var/cache/apache2/proxy
rel_proxycachedir = /var/cache/apache2/proxy
SHLTCFLAGS = -prefer-pic
LTCFLAGS = -prefer-non-pic -static
MPM_NAME = worker
MPM_SUBDIR_NAME = worker
htpasswd_LTFLAGS =
htdigest_LTFLAGS =
rotatelogs_LTFLAGS =
logresolve_LTFLAGS =
htdbm_LTFLAGS =
ab_LTFLAGS =
checkgid_LTFLAGS =
APACHECTL_ULIMIT = ulimit -S -n `ulimit -H -n`
progname = apache2
MPM_LIB = server/mpm/worker/libworker.la
OS = unix
OS_DIR = unix
BUILTIN_LIBS = modules/aaa/mod_access.la modules/aaa/mod_auth.la modules/loggers/mod_log_config.la modules/loggers/mod_logio.la modules/metadata/mod_env.la modules/metadata/mod_setenvif.la modules/http/mod_http.la modules/http/mod_mime.la modules/generators/mod_status.la modules/generators/mod_autoindex.la modules/mappers/mod_negotiation.la modules/mappers/mod_dir.la modules/mappers/mod_userdir.la modules/mappers/mod_alias.la modules/mappers/mod_so.la
SHLIBPATH_VAR = LD_LIBRARY_PATH
OS_SPECIFIC_VARS =
PRE_SHARED_CMDS = echo ""
POST_SHARED_CMDS = echo ""
shared_build = shared-build
AP_LIBS = /tmp/buildd/apache2-2.0.46/build-tree/apache2-build/worker/srclib/pcre/libpcre.la /tmp/buildd/apache2-2.0.46/build-tree/apache2-build/worker/srclib/apr-util/libaprutil-0.la -ldb -lxmlparse -lxmltok /tmp/buildd/apache2-2.0.46/build-tree/apache2-build/worker/srclib/apr/libapr-0.la -lrt -lm -lcrypt -lnsl -ldl
AP_BUILD_SRCLIB_DIRS = apr apr-util
AP_CLEAN_SRCLIB_DIRS = apr-util apr
abs_srcdir = /tmp/buildd/apache2-2.0.46/build-tree/apache2
bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
cgidir = ${prefix}/usr/lib/cgi-bin
logfiledir = ${prefix}/var/log/apache2
exec_prefix = ${prefix}/usr
datadir = ${exec_prefix}/share/apache2
localstatedir = ${prefix}/var/run
mandir = ${exec_prefix}/share/man
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/lib/apache2/modules
htdocsdir = ${prefix}/usr/share/apache2/default-site/htdocs
manualdir = ${htdocsdir}/manual
includedir = ${exec_prefix}/include/apache2
errordir = ${datadir}/error
iconsdir = ${datadir}/icons
sysconfdir = ${prefix}/etc/apache2
installbuilddir = ${prefix}/usr/share/apache2/build
runtimedir = ${prefix}/var/run
proxycachedir = ${prefix}/var/cache/apache2/proxy
other_targets = suexec
progname = apache2
prefix =
AWK = mawk
CC = gcc
CPP = gcc -E
CXX =
CPPFLAGS =
CFLAGS = -pipe -I/usr/include/xmltok -I/usr/include/openssl -O2
CXXFLAGS =
LTFLAGS = --silent
LDFLAGS =
LT_LDFLAGS = -export-dynamic
SH_LDFLAGS =
HTTPD_LDFLAGS =
UTIL_LDFLAGS =
LIBS =
DEFS =
INCLUDES =
NOTEST_CPPFLAGS = -DAP_HAVE_DESIGNATED_INITIALIZER
NOTEST_CFLAGS =
NOTEST_CXXFLAGS =
NOTEST_LDFLAGS =
NOTEST_LIBS =
EXTRA_CPPFLAGS = -DLINUX=2 -D_REENTRANT -D_XOPEN_SOURCE=500 -D_BSD_SOURCE -D_SVID_SOURCE -D_GNU_SOURCE
EXTRA_CFLAGS = -pipe -I/usr/include/xmltok -I/usr/include/openssl -O2 -pthread
EXTRA_CXXFLAGS =
EXTRA_LDFLAGS =
EXTRA_LIBS = -lz -lssl -lcrypto
EXTRA_INCLUDES = -I/usr/include/openssl -I/usr/include/apache2 -I/usr/include/apr-0
LIBTOOL = /bin/sh /usr/bin/libtool --silent
SHELL = /bin/sh
MODULE_DIRS = aaa cache experimental filters loggers metadata proxy ssl http dav/main generators dav/fs mappers
MODULE_CLEANDIRS = arch/win32 echo test
PORT = 80
nonssl_listen_stmt_1 =
nonssl_listen_stmt_2 = Listen @@Port@@
CORE_IMPLIB_FILE =
CORE_IMPLIB =
SH_LIBS =
SH_LIBTOOL = /bin/sh /usr/bin/libtool --silent
MK_IMPLIB =
INSTALL_PROG_FLAGS =
DSO_MODULES = auth_anon auth_dbm auth_digest file_cache cache disk_cache mem_cache ext_filter include deflate mime_magic cern_meta expires headers usertrack unique_id proxy proxy_connect proxy_ftp proxy_http ssl dav asis info suexec cgid cgi dav_fs vhost_alias imap actions speling rewrite
APR_BINDIR = /usr/bin
APR_INCLUDEDIR = /usr/include/apr-0
APU_BINDIR = /usr/bin
APU_INCLUDEDIR = /usr/include/apr-0
