#!/bin/sh

# Use intel on lanner boxes
if ! grep -qE 'lanner' /etc/initramfs-tools/modules ; then
    cat <<EOF > /etc/initramfs-tools/modules
# Untangle lanner bootsplash settings
intel_agp
drm
i915 modeset=1
EOF
    dpkg-trigger --no-await update-initramfs
fi

exit 0
