#!/bin/sh

deb-systemd-invoke restart untangle-hardware-config

swapNic() {
    udev_file='/etc/udev/rules.d/70-persistent-net.rules';
    echo "Moving interface ${1} to ${2}"
    perl -i -pe "s/NAME\=\"${1}\"/NAME\=\"new_${2}\"/g" $udev_file
}

swapNicFinish() {
    # then remove all the "new_".  We do the intermeidate step to avoid renaming collisions
    udev_file='/etc/udev/rules.d/70-persistent-net.rules';
    perl -i -pe "s/new_//g" $udev_file 
}

# Swap eth1 and eth2 so order is correct on faceplate
# Do this only on new install of this package
if [ -z "$2" ] ; then
    swapNic eth1 eth2
    swapNic eth2 eth1
    swapNicFinish
    swapNic eth2 eth3
    swapNic eth3 eth2
    swapNicFinish
fi

rm -f /etc/init.d/${DPKG_MAINTSCRIPT_PACKAGE}

exit 0
