#!/bin/sh

# this is creates the default wizard settings for the linksys wrt1900acs
MODEL="Linksys wrt1900acs"

if [ ! -f /usr/share/untangle/conf/wizard.js ] ; then
   echo "Initializing default wizard settings for ${MODEL}..."

   mkdir -p /usr/share/untangle/conf
   cat > /usr/share/untangle/conf/wizard.js <<EOF
{
    "javaClass": "com.untangle.uvm.WizardSettings",
    "steps": [
        "Welcome",
        "ServerSettings",
        "Internet",
        "Wireless",
        "AutoUpgrades",
        "Complete"
    ],
    "wizardComplete": false
}
EOF

   echo "Initializing default wizard settings for ${MODEL} ...done"
fi

