#! /bin/sh

set -x
set -e

# load modules
modprobe cfg80211
modprobe mac80211
modprobe ath9k
modprobe ath10k_pci

# make sure they show up in ifconfig
for i in 0 1 ; do
  ifconfig wlan${i} up
  iw dev wlan${i} set 4addr on
done

exit 0
