#! /bin/sh

set -e

#
# only some versions are supported currently
# copy all the current kernel modules in (if those kernels are installed)
#
versions="
2.6.26-1-untangle-486
2.6.26-1-untangle-686
2.6.26-1-untangle-amd64
2.6.26-2-untangle-486
2.6.26-2-untangle-686
2.6.26-2-untangle-amd64"

for version in $versions ; do
    if [ -d /lib/modules/$version ] ; then
        mkdir -p /lib/modules/$version/extra/
        cp -f /usr/share/untangle-ipset-kernel/$version/*.ko /lib/modules/$version/extra/
    fi
done

#
# Just in case - try the current kernel version
#
version=$(uname -r)
mkdir -p /lib/modules/$version/extra/
if [ -d /usr/share/untangle-ipset-kernel/$version ] ; then
    cp -f /usr/share/untangle-ipset-kernel/$version/*.ko /lib/modules/$version/extra/
fi

depmod -a
