#! /bin/sh

USER=rbot

getent passwd $USER > /dev/null || adduser --system $USER

SUDO_LINE="rbot ALL=NOPASSWD: ALL"
if grep -q rbot /etc/sudoers ; then
  perl -i -npe 's/.*rbot.*/'"$SUDO_LINE"'/' /etc/sudoers
else
  echo $SUDO_LINE >> /etc/sudoers
fi

exit 0