#!/bin/sh

# Restart postgres
# postgres seems to behave poorly on USB based systems and can get stuck creating load even while idle
if [ -f /var/run/postgresq/9.4-main.pid ] ; then
    systemctl restart postgresql
fi
