#!/bin/sh

ourInit() {
if [ -x /usr/sbin/invoke-rc.d ] && [ ! "`readlink /usr/sbin/invoke-rc.d`" = /bin/true ] ; then
  invoke-rc.d $1 $2
else
  /etc/init.d/$1 $2
fi
}

if [ -x "/etc/init.d/untangle-firmware-common" ]; then
  update-rc.d untangle-firmware-common defaults >/dev/null # early on
  ourInit untangle-firmware-common restart
fi
    
exit 0
