#!/bin/sh

if [ -x "/etc/init.d/untangle-firmware-common" ]; then
  update-rc.d untangle-firmware-common defaults >/dev/null # early on
  ourInit untangle-firmware-common restart
fi


# 12.2
# remove old scripts
rm -f /etc/untangle/hardware/firmware.d/35postgres
rm -f /etc/untangle/hardware/firmware.d/01remountroot

# 12.2
# remove old cron job
rm -f /etc/cron.hourly/sqlite

# 13.0
# delete sqlite3 DB because it doesn't support DROP COLUMN
rm -f /var/lib/sqlite/reports.db

exit 0
