#!/bin/sh

rm -f /etc/init.d/untangle-firmware-common

#DEBHELPER#

# 12.2
# remove old scripts
rm -f /etc/untangle/hardware/firmware.d/35postgres
rm -f /etc/untangle/hardware/firmware.d/01remountroot

# 12.2
# remove old cron job
rm -f /etc/cron.hourly/sqlite

# 13.0
# delete sqlite3 DB because it doesn't support DROP COLUMN
rm -f /var/lib/sqlite/reports.db

# we don't need smart disk monitoring on devices without a disk
systemctl disable smartd.service

exit 0
