#!/bin/sh
module="n22xxed"
device="n22xxed"
prog=$(basename $0)
logger="logger -t $prog"
util="/usr/sbin/n22xxed_util"
mode="664"

$logger "loading intel NIC driver kernel module"
modprobe igb
$logger "loading niagara kernel module"
modprobe $module

# Group: since distributions do it differently, look for wheel or use staff
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi

# remove stale nodes
$logger "Creating /dev/$device entry"
rm -f /dev/${device}? 

major=`cat /proc/devices | awk "\\$2==\"$module\" {print \\$1}"`

mknod /dev/${device}0 c $major 0
ln -sf ${device}0  /dev/${device}

# give appropriate group/permissions
chgrp $group /dev/${device}0
chmod $mode  /dev/${device}0
# the utility to force active mode until we go down.
$logger "Switching Card to active mode"
$util -a | $logger
