#!/bin/bash

UNTANGLESNORTCONFIG_DIR=/usr/share/untangle-snort-config

if [ ! -d "${UNTANGLESNORTCONFIG_DIR}/current/rules" ] ; then
    cd ${UNTANGLESNORTCONFIG_DIR}
    tar -xzf snortrules.tar.gz -C current
    cd -
fi

/etc/init.d/snort stop
/etc/init.d/snort-untangle stop
/usr/sbin/update-rc.d snort disable > /dev/null 2>&1
/usr/sbin/update-rc.d snort-untangle disable > /dev/null 2>&1

exit 0
