#!/bin/bash

UNTANGLESNORTCONFIG_DIR=/usr/share/untangle-snort-config

if [ ! -d "${UNTANGLESNORTCONFIG_DIR}/current/rules" ] ; then
    cd ${UNTANGLESNORTCONFIG_DIR}
    tar -xzf snortrules.tar.gz -C current
    cd -
fi

OLD_UNTANGLE_SNORT_INIT=/etc/init.d/snort-untangle
if [ -f ${OLD_UNTANGLE_SNORT_INIT} ] ; then
    systemctl stop snort-untangle
    systemctl disable snort-untangle > /dev/null 2>&1
    rm -f ${OLD_UNTANGLE_SNORT_INIT}
fi

exit 0
